In [4]:
%pip install pandas             
# Biblioteca principal para manipulação e análise de dados estruturados
%pip install openpyxl           
# Dependência do Pandas para leitura de arquivos .xlsx
%pip install rich               
# Estilização avançada e formatação de outputs no terminal/notebook
%pip install SQLAlchemy

Requirement already satisfied: pandas in /home/fald/Projeto-Pipeline---PROCONS-Sindec/.venv/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /home/fald/Projeto-Pipeline---PROCONS-Sindec/.venv/lib/python3.12/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/fald/Projeto-Pipeline---PROCONS-Sindec/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/fald/Projeto-Pipeline---PROCONS-Sindec/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: openpyxl in /home/fald/Projeto-Pipeline---PROCONS-Sindec/.venv/lib/python3.12/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /home/fald/Projeto-Pipeline---PROCONS-Sindec/.venv/lib/python3.12/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: rich in /home/fald/Projeto-Pipeline---PROCONS-Sindec/.venv/lib/python3.12/site-packages (15.0.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /home/fald/Projeto-Pipeline---PROCONS-Sindec/.venv/lib/python3.12/site-packages (from rich) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /home/fald/Projeto-Pipeline---PROCONS-Sindec/.venv/lib/python3.12/site-packages (from rich) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /home/fald/Projeto-Pipeline---PROCONS-Sindec/.venv/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich) (0.1.2)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: SQLAlchemy in /home/fald/Projeto-Pipeline---PROCONS-Sindec/.venv/lib/python3.12/site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in /home/fald/Projeto-Pipeline---PROCONS-Sindec/.venv/lib/python3.12/site-packages (from SQLAlchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in /home/fald/Projeto-Pipeline---PROCONS-Sindec/.venv/lib/python3.12/site-packages (from SQLAlchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [5]:
import pandas as pd

from rich import print
from rich.panel import Panel
from rich.table import Table
from rich.console import Console

# 1. Pipeline de Extração de Dados (Data Extraction)
O objetivo desta etapa é consolidar os múltiplos arquivos dispersos do Cadastro Nacional de Reclamações Fundamentadas (2009-2024) em uma estrutura unificada (DataFrame). 

Durante a extração, os seguintes tratamentos preliminares são aplicados:
* **Padronização de Cabeçalhos:** Conversão para minúsculas e mapeamento manual para o arquivo de 2017 (ausência de *header*).
* **Tratamento de Exceções (`on_bad_lines`):** Descarte de linhas com corrupção estrutural (vazamento de delimitadores) para garantir a integridade do *Data Warehouse*.
* **Rastreabilidade:** Injeção do metadado `ano_origem` para preservar a linhagem dos dados.

In [6]:
# Definindo o padrão de colunas (tudo em minúsculo) para forçar em todos os arquivos (principalmente em 2017 que está sem header)
colunas_padrao = [
    'anocalendario', 'dataarquivamento', 'dataabertura', 'codigoregiao', 'regiao',
    'uf', 'strrazaosocial', 'strnomefantasia', 'tipo', 'numerocnpj', 'radicalcnpj',
    'razaosocialrfb', 'nomefantasiarfb', 'cnaeprincipal', 'desccnaeprincipal',
    'atendida', 'codigoassunto', 'descricaoassunto', 'codigoproblema',
    'descricaoproblema', 'sexoconsumidor', 'faixaetariaconsumidor', 'cepconsumidor'
]

# Para evitarmos erros de leitura futuros
colunas_removidas = []


# Criando um dicionário com todos os caminhos dos arquivos, baseando-se no ano de cada arquivo
arquivos = {
    '2009': '../dados_brutos/CNRF_2009.csv',
    '2010': '../dados_brutos/CNRF_2010.csv',
    '2011': '../dados_brutos/CNRF_2011.csv',
    '2012': '../dados_brutos/CNRF_2012.csv',
    '2013': '../dados_brutos/CNRF_2013.csv',
    '2014': '../dados_brutos/CNRF_2014.csv',
    '2015': '../dados_brutos/CNRF_2015.csv',
    '2016': '../dados_brutos/CNRF_2016.csv',
    '2017': '../dados_brutos/CNRF_2017.csv',
    '2018': '../dados_brutos/CNRF_2018.csv',
    '2019': '../dados_brutos/CNRF_2019.csv',
    '2020': '../dados_brutos/CNRF_2020.csv',
    '2021': '../dados_brutos/CNRF_2021.csv',
    '2022': '../dados_brutos/CNRF_2022.csv',
    '2023': '../dados_brutos/CNRF_2023.csv',
    '2024': '../dados_brutos/CNRF_2024.xlsx'
}

lista_dataframes = []                       # Para armazenar os dataframes até podermos agregá-los em um só
total_linhas_brutas = 0                     # Contadores para aferirmos se estamos perdendo muitas linhas
total_linhas_limpas = 0

print("Iniciando a Extração de Dados dos arquivos CNRF...\n")

for ano, caminho_arquivo in arquivos.items():
    linhas_no_arquivo   = 0
    linhas_lidas_pandas = 0
    
    try:
        ### CONTAGEM BRUTA
        if caminho_arquivo.endswith('.csv'):
            # Lendo o arquivo como texto puro apenas para contar as linhas
            with open(caminho_arquivo, 'r', encoding='latin1') as f:
                linhas_no_arquivo = sum(1 for linha in f)
            
            # Subtraindo a primeira linha (header), exceto para 2017 que não tem 
            if ano != '2017':
                linhas_no_arquivo -= 1
                
        elif caminho_arquivo.endswith('.xlsx'):
            # No casos especial do arquivo em excel, vamos deixar o Pandas lidar sozinho com a contagem bruta
            df_temp = pd.read_excel(caminho_arquivo, dtype=str)
            linhas_no_arquivo = len(df_temp)

        ### LEITURA E LIMPEZA INICIAL COM PANDAS
        if caminho_arquivo.endswith('.csv'):
            if ano == '2017':
                # Caso especial em que o arquivo não apresenta header
                df = pd.read_csv(caminho_arquivo, encoding='latin1', sep=';', header=None, names=colunas_padrao, dtype=str, on_bad_lines='skip')
            else:
                # Caso comum em que o arquivo apresenta header
                df = pd.read_csv(caminho_arquivo, encoding='latin1', sep=';', dtype=str, on_bad_lines='skip')
                df.columns = colunas_padrao # Forçando o padrão
                
        elif caminho_arquivo.endswith('.xlsx'):
            df = df_temp # Aproveitando que o arquivo já foi lido
            df.columns = colunas_padrao # Forçando o padrão
        
        ### FINALIZAÇÃO DO ARQUIVO
        df['ano_origem'] = ano
        lista_dataframes.append(df)
        
        linhas_lidas_pandas = len(df)
        linhas_perdidas = linhas_no_arquivo - linhas_lidas_pandas
        
        # Atualização dos contadores globais
        total_linhas_brutas += linhas_no_arquivo
        total_linhas_limpas += linhas_lidas_pandas
        
        print(f"[bold cyan][{ano}][/] - Brutas: [blue]{linhas_no_arquivo:<7}[/] | Salvas: [green]{linhas_lidas_pandas:<7}[/] | Perdidas: [red]{linhas_perdidas}[/]")

    except Exception as e:
        print(f"[{ano}] - Erro Crítico: {e}")

### PRINT DOS RESULTADOS DA AUDITORIA
df_final = pd.concat(lista_dataframes, ignore_index=True)

taxa_perda = ((total_linhas_brutas - total_linhas_limpas) / total_linhas_brutas) * 100 if total_linhas_brutas > 0 else 0

print("-" * 40)
print("RESUMO DA EXTRAÇÃO")
print(f"Total de registros originais: {total_linhas_brutas}")
print(f"Total de registros recuperados: {total_linhas_limpas}")
print(f"Total de registros descartados: {total_linhas_brutas - total_linhas_limpas}")
print(f"Taxa de perda de dados: {taxa_perda:.4f}%")
print("-" * 40)

Iniciando a Extração de Dados dos arquivos CNRF...

[2009] - Brutas: 104869  | Salvas: 104869  | Perdidas: 0

[2010] - Brutas: 122664  | Salvas: 122664  | Perdidas: 0

[2011] - Brutas: 153096  | Salvas: 153096  | Perdidas: 0

[2012] - Brutas: 211076  | Salvas: 211076  | Perdidas: 0

[2013] - Brutas: 268096  | Salvas: 268096  | Perdidas: 0

[2014] - Brutas: 267764  | Salvas: 267764  | Perdidas: 0

[2015] - Brutas: 255650  | Salvas: 255650  | Perdidas: 0

[2016] - Brutas: 203485  | Salvas: 203485  | Perdidas: 0

[2017] - Brutas: 42307   | Salvas: 42307   | Perdidas: 0

[2018] - Brutas: 39060   | Salvas: 39047   | Perdidas: 13

[2019] - Brutas: 17577   | Salvas: 17555   | Perdidas: 22

[2020] - Brutas: 8016    | Salvas: 8006    | Perdidas: 10

[2021] - Brutas: 9007    | Salvas: 9007    | Perdidas: 0

[2022] - Brutas: 68303   | Salvas: 68289   | Perdidas: 14

[2023] - Brutas: 17266   | Salvas: 17266   | Perdidas: 0

[2024] - Brutas: 13803   | Salvas: 13803   | Perdidas: 0

----------------------------------------

RESUMO DA EXTRAÇÃO

Total de registros originais: 1802039

Total de registros recuperados: 1801980

Total de registros descartados: 59

Taxa de perda de dados: 0.0033%

----------------------------------------

# 2. Análise Exploratória e Diagnóstico de Dados (EDA)
Antes de iniciarmos os processos de transformação (Limpeza e Modelagem Dimensional), é crucial inspecionar a saúde estrutural da base consolidada, verificando os tipos inferidos, o consumo de memória e a integridade das instâncias.

In [7]:
# Verificando a estrutura do DataFrame consolidado
with pd.option_context('display.max_columns', None):
    display(df_final.head(5))
    
print("\n")
df_final.info()

print("\n--- Contagem de Valores Únicos por Coluna ---")
display(df_final.nunique(dropna=False))

,anocalendario,dataarquivamento,dataabertura,codigoregiao,regiao,uf,strrazaosocial,strnomefantasia,tipo,numerocnpj,radicalcnpj,razaosocialrfb,nomefantasiarfb,cnaeprincipal,desccnaeprincipal,atendida,codigoassunto,descricaoassunto,codigoproblema,descricaoproblema,sexoconsumidor,faixaetariaconsumidor,cepconsumidor,ano_origem
0,2009,2009-01-21 15:29:29.000,2005-07-06 08:32:23.000,05,Centro-oeste,GO,CBP SUL - COLCHÕES E ESPUMAS INDUSTRIAIS LTDA,LIMANSKY,1,01350934000116,01350934,CBP SUL - COLCHOES E ESPUMAS INDUSTRIAIS LTDA,NaN,3104700,FABRICAÇÃO DE COLCHÕES,S,100,Colchão,105,Produto entregue com danos/defeitos,M,entre 61 a 70 anos,74680330,2009
1,2009,2009-05-12 12:05:08.000,2006-01-17 12:10:53.000,03,Sudeste,RJ,GRADIENTE,NaN,1,43185362001936,43185362,IGB ELETRONICA S.A,NaN,2640000,"FABRICAÇÃO DE APARELHOS DE RECEPÇÃO, REPRODUÇÃ...",N,146,Aparelho DVD,107,Não entrega/demora na entrega do produto,F,entre 51 a 60 anos,23510240,2009
2,2009,2009-04-23 08:52:31.000,2005-07-06 11:28:47.000,05,Centro-oeste,GO,IGL INDÚSTRIA LTDA,ELIDA PONDS INDUSTRIAL LTDA,1,03085759000102,03085759,UNILEVER BRASIL HIGIENE PESSOAL E LIMPEZA LTDA,ELIDA PONDS INDUSTRIAL LTDA.,2063100,"FABRICAÇÃO DE COSMÉTICOS, PRODUTOS DE PERFUMAR...",N,224,Produto Para Uso Veterinário ( Medicamento / S...,177,Presença de sujidades/corpos estranhos,F,entre 21 a 30 anos,74775010,2009
3,2009,2009-04-23 08:52:31.000,2005-07-06 11:28:47.000,05,Centro-oeste,GO,UNILEVER BESTFOODS BRASIL LTDA,UNILEVER,1,01615814002066,01615814,UNILEVER BRASIL INDUSTRIAL LTDA,NaN,1031700,FABRICAÇÃO DE CONSERVAS DE FRUTAS,N,224,Produto Para Uso Veterinário ( Medicamento / S...,177,Presença de sujidades/corpos estranhos,F,entre 21 a 30 anos,74775010,2009
4,2009,2009-07-23 11:57:40.000,2006-01-18 15:35:29.000,03,Sudeste,RJ,EMPRESA BRASILEIRA DE TELECOMUNICAÇÕES S.A,EMBRATEL - LIVRE,1,33530486000129,33530486,EMPRESA BRASILEIRA DE TELECOMUNICACOES S A EMB...,NaN,6110899,SERVIÇOS DE TELECOMUNICAÇÕES POR FIO NÃO ESPEC...,S,186,Telefonia Fixa ( Plano de Expansão / Compra e ...,143,Contrato - Rescisão/alteração unilateral,F,entre 41 a 50 anos,20710270,2009

<class 'pandas.DataFrame'>
RangeIndex: 1801980 entries, 0 to 1801979
Data columns (total 24 columns):
 #   Column                 Dtype
---  ------                 -----
 0   anocalendario          str
 1   dataarquivamento       str
 2   dataabertura           str
 3   codigoregiao           str
 4   regiao                 str
 5   uf                     str
 6   strrazaosocial         str
 7   strnomefantasia        str
 8   tipo                   str
 9   numerocnpj             str
 10  radicalcnpj            str
 11  razaosocialrfb         str
 12  nomefantasiarfb        str
 13  cnaeprincipal          str
 14  desccnaeprincipal      str
 15  atendida               str
 16  codigoassunto          str
 17  descricaoassunto       str
 18  codigoproblema         str
 19  descricaoproblema      str
 20  sexoconsumidor         str
 21  faixaetariaconsumidor  str
 22  cepconsumidor          str
 23  ano_origem             str
dtypes: str(24)
memory usage: 330.0 MB

--- Contagem de Valores Únicos por Coluna ---

anocalendario                 21
dataarquivamento         1109174
dataabertura             1434018
codigoregiao                  11
regiao                         6
uf                            27
strrazaosocial            179075
strnomefantasia           124804
tipo                           3
numerocnpj                133214
radicalcnpj               103925
razaosocialrfb             91540
nomefantasiarfb            57350
cnaeprincipal               1029
desccnaeprincipal           1715
atendida                       3
codigoassunto                245
descricaoassunto             375
codigoproblema              3782
descricaoproblema            374
sexoconsumidor                 4
faixaetariaconsumidor         11
cepconsumidor             305552
ano_origem                    16
dtype: int64

### 2.1. Diagnóstico Detalhado por Coluna
Análise individual dos valores únicos das variáveis categóricas para mapear inconsistências de tipagem, erros de digitação e ruídos gerados na origem governamental.

In [8]:
# Analisando os valores únicos e a contagem de valores nulos para fundamentar o plano de limpeza
print(Panel("[bold bright_magenta]DIAGNÓSTICO DE VALORES ÚNICOS E NULOS POR COLUNA[/]", expand=False))

# Função auxiliar para padronizar o print e manter tudo alinhado
def print_diagnostico(nome_coluna):
    valores_unicos = df_final[nome_coluna].unique()
    qtd_nulos = df_final[nome_coluna].isnull().sum()
    print(f"[bold cyan]{nome_coluna:<22}[/]| Nulos: [bold red]{qtd_nulos:<6}[/]\n{valores_unicos}\n" + "-" * 80)


for col in colunas_padrao:
    if col not in colunas_removidas:
        print_diagnostico(col)

╭──────────────────────────────────────────────────╮
│ DIAGNÓSTICO DE VALORES ÚNICOS E NULOS POR COLUNA │
╰──────────────────────────────────────────────────╯

anocalendario         | Nulos: 3
<StringArray>
[                    '2009',                        nan,
 '(104867 row(s) affected)',                     '2010',
 '(122662 row(s) affected)',                     '2011',
 '(153094 row(s) affected)',                     '2012',
                     '2013',                     '2014',
                     '2015',                     '2016',
                  'ï»¿2017',                     '2017',
                     '2018',                     '2019',
                     '2020',                     '2021',
                     '2022',                     '2023',
                     '2024']
Length: 21, dtype: str
--------------------------------------------------------------------------------

dataarquivamento      | Nulos: 35
<StringArray>
['2009-01-21 15:29:29.000', '2009-05-12 12:05:08.000',
 '2009-04-23 08:52:31.000', '2009-07-23 11:57:40.000',
 '2009-04-24 16:06:37.000', '2008-11-12 12:11:14.000',
 '2008-09-19 14:55:28.000', '2008-10-29 16:16:40.000',
 '2008-10-21 08:04:34.000', '2008-09-25 12:01:51.000',
 ...
 '2024-04-11 10:55:03.000', '2024-04-04 10:33:49.000',
 '2024-05-09 10:04:25.000', '2024-04-02 11:50:48.000',
 '2024-05-27 11:22:30.000', '2024-04-01 14:02:54.000',
 '2024-03-04 09:53:08.000', '2024-05-02 16:49:10.000',
 '2024-03-04 16:02:39.000', '2024-04-10 12:51:57.000']
Length: 1109174, dtype: str
--------------------------------------------------------------------------------

dataabertura          | Nulos: 22
<StringArray>
['2005-07-06 08:32:23.000', '2006-01-17 12:10:53.000',
 '2005-07-06 11:28:47.000', '2006-01-18 15:35:29.000',
 '2005-07-06 15:36:03.000', '2006-01-23 12:58:47.000',
 '2005-03-28 10:20:39.000', '2005-03-31 09:59:40.000',
 '2005-07-08 15:19:39.000', '2005-07-08 15:46:05.000',
 ...
 '2024-03-04 08:09:59.000', '2024-02-29 08:12:41.000',
 '2024-03-26 16:40:32.000', '2024-02-20 11:39:28.000',
 '2024-03-21 10:18:22.000', '2024-01-24 09:49:10.000',
 '2024-01-29 13:30:56.000', '2024-02-02 08:41:32.000',
 '2024-01-26 09:41:28.000', '2024-02-06 12:10:56.000']
Length: 1434018, dtype: str
--------------------------------------------------------------------------------

codigoregiao          | Nulos: 6
<StringArray>
['05', '03', '01', '04', '02', nan, '2', '3', '4', '5', '1']
Length: 11, dtype: str
--------------------------------------------------------------------------------

regiao                | Nulos: 6
<StringArray>
['Centro-oeste', 'Sudeste', 'Norte', 'Sul', 'Nordeste', nan]
Length: 6, dtype: str
--------------------------------------------------------------------------------

uf                    | Nulos: 6
<StringArray>
['GO', 'RJ', 'PA', 'AP', 'SC', 'MT', 'AM', 'PB', 'BA', 'ES', 'MS', 'PE', 'PI',
 'RN', 'CE', 'MG', 'AC', 'AL', 'SE', 'DF', 'MA', 'TO',  nan, 'RS', 'SP', 'PR',
 'RO']
Length: 27, dtype: str
--------------------------------------------------------------------------------

strrazaosocial        | Nulos: 19
<StringArray>
[   'CBP SUL - COLCHÕES E ESPUMAS INDUSTRIAIS LTDA',
                                        'GRADIENTE',
                               'IGL INDÚSTRIA LTDA',
                   'UNILEVER BESTFOODS BRASIL LTDA',
       'EMPRESA BRASILEIRA DE TELECOMUNICAÇÕES S.A',
                 'LG ELECTRONICS DE SAO PAULO LTDA',
                          'MOTOROLA DO BRASIL LTDA',
                                  'TIM CELULAR S/A',
                          'PONTE IRMÃO & CIA LTDA.',
                                     'AMERICEL S/A',
 ...
                 'ERIKE DE OLIVEIRA SA 22942544813',
                              'MERCALF DIESEL LTDA',
   'RALIC CONSULTORIA E CORRETAGEM DE SEGUROS LTDA',
       'OWEM PAY INTERMEDIADORA DE PAGAMENTOS LTDA',
              'N26 SOCIEDADE DE CREDITO DIRETO S.A',
 'CENTRO DE FORMACAO DE C. FORTAL AUTO ESCOLA LTDA',
              'CERT CAR COMERCIO DE VEICULOS LTDA.',
                          'AGIL SECURITIZADORA S A',
     'CRYSTAL ESQUADRIAS DE ALUMINIO E VIDROS LTDA',
                            'R R DE SOUSA MENDONCA']
Length: 179075, dtype: str
--------------------------------------------------------------------------------

strnomefantasia       | Nulos: 295958
<StringArray>
[                               'LIMANSKY',
                                       nan,
             'ELIDA PONDS INDUSTRIAL LTDA',
                                'UNILEVER',
                        'EMBRATEL - LIVRE',
                                      'LG',
                 'MOTOROLA DO BRASIL LTDA',
                                     'TIM',
                         'LOJAS ESPLANADA',
                             'TIM CELULAR',
 ...
                                  'VOOFIT',
                         'PREMIUM TURISMO',
                             'ERIKE PECAS',
                          'MERCALF DIESEL',
                                'OWEM PAY',
     'N26 SOCIEDADE DE CREDITO DIRETO S.A',
                          'CERT CAR STORE',
 'CRYSTAL ESQUADRIAS DE ALUMINIO E VIDROS',
                'HUGO BOSS DO BRASIL LTDA',
                       'VERTICAL VEICULOS']
Length: 124804, dtype: str
--------------------------------------------------------------------------------

tipo                  | Nulos: 6
<StringArray>
['1', '0', nan]
Length: 3, dtype: str
--------------------------------------------------------------------------------

numerocnpj            | Nulos: 76699
<StringArray>
['01350934000116', '43185362001936', '03085759000102', '01615814002066',
 '33530486000129', '01166372000155', '62288584000108', '04206050002809',
 '04228987008212', '04206050005220',
 ...
 '28091373000134',  '4807924000740', '10198495000169', '37839059000188',
 '40867163000190', '31801065000160', '35078477000174', '49000822000161',
 '57621054001910', '36556368000188']
Length: 133214, dtype: str
--------------------------------------------------------------------------------

radicalcnpj           | Nulos: 78756
<StringArray>
['01350934', '43185362', '03085759', '01615814', '33530486', '01166372',
 '62288584', '04206050', '04228987', '01685903',
 ...
 '10198495', '37839059', '40867163',  '2038584',  '1338617', '31801065',
 '35078477', '49000822',  '4620772', '36556368']
Length: 103925, dtype: str
--------------------------------------------------------------------------------

razaosocialrfb        | Nulos: 120540
<StringArray>
[      'CBP SUL - COLCHOES E ESPUMAS INDUSTRIAIS LTDA',
                                  'IGB ELETRONICA S.A',
      'UNILEVER BRASIL HIGIENE PESSOAL E LIMPEZA LTDA',
                     'UNILEVER BRASIL INDUSTRIAL LTDA',
 'EMPRESA BRASILEIRA DE TELECOMUNICACOES S A EMBRATEL',
                       'LG ELECTRONICS DO BRASIL LTDA',
                             'MOTOROLA DO BRASIL LTDA',
                                    'TIM CELULAR S.A.',
                              'PONTE IRMAO E CIA LTDA',
                                        'AMERICEL S/A',
 ...
                   'INSTITUTO ALCIDES D' ANDRADE LIMA',
              'ITAREMA AUTO PECAS SOROCABA LTDA  - ME',
                  'RAIMUNDO FERREIRA DIAS 00189110309',
                         'GODOY MOTO RACING LTDA - ME',
                   'METALOSA INDUSTRIA METALURGICA SA',
                          'NOVA GESTAO HOTELARIA LTDA',
                 'M. P. INSTITUTO LINGUISTICO LTDA ME',
                           'CENTRO DOS OCULOS LTDA ME',
             'PREMIUM TL TURISMO E NEGOCIOS LTDA - ME',
      'RALIC CONSULTORIA E CORRETAGEM DE SEGUROS LTDA']
Length: 91540, dtype: str
--------------------------------------------------------------------------------

nomefantasiarfb       | Nulos: 990940
<StringArray>
[                            nan,  'ELIDA PONDS INDUSTRIAL LTDA.',
                           'TIM',                     'ESPLANADA',
              'TIM CELULAR S.A.',                         'CLARO',
                'RICARDO ELETRO',            'LIDER REFRIGERACAO',
                          'VIVO',                 'DIRECAO GERAL',
 ...
                  'BRUMA TELHAS',                       'VALANNA',
               'MERCADINHO REAL',  'HOSPITAL MEMORIAL GUARARAPES',
            'ITAVEMA AUTO PECAS',       'CN SEGURANCA ELETRONICA',
             'GODOY MOTO RACING',                      'METALOSA',
                       'LEXICAL', 'PAULO TIBERIO PESSOA NOGUEIRA']
Length: 57350, dtype: str
--------------------------------------------------------------------------------

cnaeprincipal         | Nulos: 124602
<StringArray>
['3104700', '2640000', '2063100', '1031700', '6110899', '2622100', '4752100',
 '6120501', '4755502', '9521500',
 ...
 '4622200', '4681802', '3240002', '0111399', '4637104',  '220902',  '311604',
  '151201',  '810099', '1111902']
Length: 1029, dtype: str
--------------------------------------------------------------------------------

desccnaeprincipal     | Nulos: 142922
<StringArray>
[                                                                                                       'FABRICAÇÃO
DE COLCHÕES',
                                     'FABRICAÇÃO DE APARELHOS DE RECEPÇÃO, REPRODUÇÃO, GRAVAÇÃO E AMPLIFICAÇÃO DE
ÁUDIO E VÍDEO',
                                                         'FABRICAÇÃO DE COSMÉTICOS, PRODUTOS DE PERFUMARIA E DE
HIGIENE PESSOAL',
                                                                                             'FABRICAÇÃO DE
CONSERVAS DE FRUTAS',
                                                          'SERVIÇOS DE TELECOMUNICAÇÕES POR FIO NÃO ESPECIFICADOS
ANTERIORMENTE',
                                                                    'FABRICAÇÃO DE PERIFÉRICOS PARA EQUIPAMENTOS DE
INFORMÁTICA',
                                                   'COMÉRCIO VAREJISTA ESPECIALIZADO DE EQUIPAMENTOS DE TELEFONIA E
COMUNICAÇÃO',
                                                                                                       'TELEFONIA
MÓVEL CELULAR',
                                                                                    'COMERCIO VAREJISTA DE ARTIGOS
DE ARMARINHO',
                                           'REPARAÇÃO E MANUTENÇÃO DE EQUIPAMENTOS ELETROELETRÔNICOS DE USO PESSOAL
E DOMÉSTICO',
 ...
 'FABRICAÇÃO DE APARELHOS E UTENSÍLIOS PARA CORREÇÃO DE DEFEITOS FÍSICOS E APARELHOS ORTOPÉDICOS EM GERAL, EXCETO
SOB ENCOMENDA',
                                                                         'FABRICAÇÃO DE OUTRAS AGUARDENTES E
BEBIDAS DESTILADAS',
                                              'AGENCIAMENTO DE PROFISSIONAIS PARA ATIVIDADES ESPORTIVAS, CULTURAIS
E ARTÍSTICAS',
                                                  'FABRICAÇÃO DE GERADORES DE CORRENTE CONTÍNUA E ALTERNADA, PEÇAS
E ACESSÓRIOS',
          'SERVIÇOS DE OPERAÇÃO E FORNECIMENTO DE EQUIPAMENTOS PARA TRANSPORTE E ELEVAÇÃO DE CARGAS E PESSOAS PARA
USO EM OBRAS',
                                                                                          'COMÉRCIO ATACADISTA DE
LUBRIFICANTES',
                                                                                             'FABRICAÇÃO DE MASSAS
ALIMENTÍCIAS',
                                                              'FABRICAÇÃO DE SUCOS CONCENTRADOS DE FRUTAS,
HORTALIÇAS E LEGUMES',
                                                               'FABRICAÇÃO DE MOTORES PARA AUTOMÓVEIS, CAMIONETAS E
UTILITÁRIOS',
                                                                       'COMÉRCIO ATACADISTA DE CIGARROS,
CIGARRILHAS E CHARUTOS']
Length: 1715, dtype: str
--------------------------------------------------------------------------------

atendida              | Nulos: 6
<StringArray>
['S', 'N', nan]
Length: 3, dtype: str
--------------------------------------------------------------------------------

codigoassunto         | Nulos: 20
<StringArray>
['100', '146', '224', '186', '101', '187',  '92',  '95',  '54', '103',
 ...
  '11',  '46', '209',  '40',  '32',  '41',  '52',  '47',  '43',  '44']
Length: 245, dtype: str
--------------------------------------------------------------------------------

descricaoassunto      | Nulos: 20
<StringArray>
[
'Colchão',

                     'Aparelho DVD',
                                                                                   'Produto Para Uso Veterinário (
Medicamento / Sabonete / Shampoo )',
                                                                                     'Telefonia Fixa ( Plano de
Expansão / Compra e Venda / Locação )',
                                                                                                 'Telefone (
Convencional, Celular, Interfone, Etc. )',

                'Telefonia Celular',
                                                                                                           'Máquina
de Lavar Roupa / Louça e Secadora',
                                                                                                               'Apa
relho de Som ( Gravador, 3x1, CD )',

                'Cartão de Crédito',
                                                   'Artigo de Cozinha ( Coifa, Exaustor, Panela, Talher, Filtro de
Café, Porta-Filtro, Louças, Etc. )',
 ...
                                                                                             'Tomate e derivados
(in natura, extratos, molhos, polpa)',
                                    'Especiarias e Condimentos (orÃ©gano, pimenta, cravo, canela, pÃ¡prica, noz
moscada, alho e cebola desidratados).',
                                                                                               'Sopas
(desidratadas, liofilizadas, latas e embaladas)',

            'CartÃµes de Descontos',
                                                                                                    'Temperos
prontos (ajinomoto, sal com alho, etc.)',
                                                                                                      'Venda
atravÃ©s de reembolso postal a domicilio',

                              'Sal',

                          'Vinagre',

             'Cartões de Descontos',
 'Domissanitário / Saneante ( Desinfetante / Detergente / Cera / Creolina / Sabão / Água Sanitária ) Desinfetante (
Inseticida / Raticida Doméstico )']
Length: 375, dtype: str
--------------------------------------------------------------------------------

codigoproblema        | Nulos: 65511
<StringArray>
[ '105',  '107',  '177',  '143',  '102',  '123',  '134',  '113',   '28',
  '194',
 ...
 '6920',  '729',  '276', '5553', '6660', '3699', '4778', '4286', '2250',
 '1463']
Length: 3782, dtype: str
--------------------------------------------------------------------------------

descricaoproblema     | Nulos: 65511
<StringArray>
[                                                                          'Produto entregue com danos/defeitos',
                                                                      'Não entrega/demora na entrega do produto',
                                                                        'Presença de sujidades/corpos estranhos',
                                                                      'Contrato - Rescisão/alteração unilateral',
                                                                       'Garantia (Abrangência, cobertura, etc.)',
                                                     'Vicio de qualidade (mal executado, inadequado, impróprio)',
                                                                                     'Cobrança indevida/abusiva',
                                                                                    'Falta de peca de reposição',
                                                                                            'Cobrança indevida.',
                                'Documentos: não fornecimento (escolares, recibo, nota, fiscal, vaucher , etc.)',
 ...
                                               'Qualidade da construção (vícios, vazamentos, impermeabilização)',
                                     'Acidente de Consumo (produto/serviço causou danos pessoais ao consumidor)',
                                      'Tarifa de Cartão de Crédito – Cobrança Indevida (anuidade, 2ª via, etc.)',
                                                                  'Tarifas Bancárias – Cobrança não autorizada.',
                'Tarifas Bancárias – Divulgação inadequada / não divulgação na agência ou no sítio da Internet.',
                                         'CET – Divulgação inadequada / não divulgação nas peças publicitárias.',
 'SAC – Acesso ao serviço (onerosidade, problemas no menu, indisponibilidade, inacessibilidade aos deficientes)',
                                    'SAC – Cancelamento de serviço (retenção, demora, não envio do comprovante)',
                                            'CET – Não fornecimento de planilha de cálculo / Recusa de cálculo.',
      'SAC – Resolução de demandas (ausência de resposta, excesso de prazo, não suspensão imediata da cobrança)']
Length: 374, dtype: str
--------------------------------------------------------------------------------

sexoconsumidor        | Nulos: 1029
<StringArray>
['M', 'F', 'N', nan]
Length: 4, dtype: str
--------------------------------------------------------------------------------

faixaetariaconsumidor | Nulos: 6
<StringArray>
['entre 61 a 70 anos', 'entre 51 a 60 anos', 'entre 21 a 30 anos',
 'entre 41 a 50 anos', 'entre 31 a 40 anos',    'mais de 70 anos',
      'Nao Informada',        'até 20 anos',                  nan,
      'Nao se aplica',       'atÃ© 20 anos']
Length: 11, dtype: str
--------------------------------------------------------------------------------

cepconsumidor         | Nulos: 132882
<StringArray>
['74680330', '23510240', '74775010', '20710270', '74000000', '26480440',
 '66030130',        nan, '75200000', '74230110',
 ...
 '75513466', '60830080', '60714690', '60530080', '60020260', '60525004',
 '60834560', '60740545', '60360575', '60440544']
Length: 305552, dtype: str
--------------------------------------------------------------------------------

# 3. Plano de Ação para Transformação (Data Cleaning)
A análise exploratória das variáveis revelou inconsistências críticas nos registros brutos. A redundância de valores nulos simultâneos (6 registros) indica a presença de linhas fantasmas derivadas de logs de banco de dados da origem (ex: `(104867 row(s) affected)`). 

Para garantir a qualidade da base antes da modelagem em Esquema Estrela, as seguintes transformações serão aplicadas nesta ordem:

1.  **Limpeza Global de Ruídos:** Remoção das instâncias vazias/corrompidas geradas por metadados da exportação original, que afetam simultaneamente as colunas `regiao`, `uf`, `tipo`, `atendida` e `faixaetariaconsumidor`.
<br><br>

2.  **`anocalendario`:** A coluna será descartada (Drop). A coluna `ano_origem`, gerada no pipeline de extração, encontra-se totalmente íntegra e assumirá a função de eixo temporal primário.
<br><br>

3.  **`codigoregiao`:** Padronização da máscara numérica. Entradas do tipo `'0X'` serão tratadas e convertidas para o padrão inteiro `'X'`.
<br><br>

4.  **`sexoconsumidor`:** Padronização categórica. Entradas irregulares (`'N'`) e valores nulos (`NaN`) serão unificados sob a categoria `'OUTROS'`.
<br><br>

5.  **`faixaetariaconsumidor`:** A coluna passará por uma higienização textual profunda em uma etapa isolada devido à alta variabilidade tipográfica e de formatação.
<br><br>

6.  **Outras colunas:** Análise será feita caso à caso, focando na eliminação de linhas que possam quebrar o esquema estrela.

In [9]:
print(Panel("[bold bright_magenta]Iniciando a Limpeza Inicial dos Dados...[/]", expand=False))

# Tamanho original para calcularmos as métricas de perda
quantidade_linhas_antes = len(df_final) 



### Descarte do 'anocalendario'
df_final = df_final.drop(columns=['anocalendario'], errors='ignore')
colunas_removidas.append("anocalendario")


### Limpeza Global de Ruídos (NaN)
df_final.dropna(how='all', inplace=True) # Linhas completamente vazias
df_final = df_final.dropna(subset=['codigoregiao', 'regiao', 'uf', 'tipo', 'atendida', 'faixaetariaconsumidor'])


### Padronização do 'codigoregiao' | 0X -> X
padrao_codigo_regiao = {
    "01" : "1", 
    "02" : "2", 
    "03" : "3", 
    "04" : "4", 
    "05" : "5"
}
df_final['codigoregiao'] = df_final['codigoregiao'].replace(padrao_codigo_regiao) # Faz a substituição conforme o dicionário 'padrao_codigo_regiao'


### Padronização do 'sexoconsumidor' | N, NaN -> OUTROS
df_final['sexoconsumidor'] = df_final['sexoconsumidor'].fillna("OUTROS") # Preenche valores nulos (NaN)
df_final['sexoconsumidor'] = df_final['sexoconsumidor'].replace({"N" : "OUTROS"})


### PRINT DOS RESULTADOS DA AUDITORIA
linhas_descartadas = quantidade_linhas_antes - len(df_final)
porcentagem_perda = (linhas_descartadas / quantidade_linhas_antes) * 100 if quantidade_linhas_antes > 0 else 0

print(f"[bold green]Limpeza concluída com sucesso![/]")
print(f"Total de linhas antes:  [cyan]{quantidade_linhas_antes}[/]")
print(f"Total de linhas válidas:[bold cyan] {len(df_final)}[/]")
print(f"Linhas descartadas:     [red]{linhas_descartadas}[/] ({porcentagem_perda:.4f}%)")
print("-" * 60)


for col in colunas_padrao:
    if col not in colunas_removidas:
        print_diagnostico(col)

print("\n--- Contagem de Valores Únicos por Coluna ---")
display(df_final.nunique(dropna=False))

╭──────────────────────────────────────────╮
│ Iniciando a Limpeza Inicial dos Dados... │
╰──────────────────────────────────────────╯

Limpeza concluída com sucesso!

Total de linhas antes:  1801980

Total de linhas válidas: 1801974

Linhas descartadas:     6 (0.0003%)

------------------------------------------------------------

dataarquivamento      | Nulos: 29
<StringArray>
['2009-01-21 15:29:29.000', '2009-05-12 12:05:08.000',
 '2009-04-23 08:52:31.000', '2009-07-23 11:57:40.000',
 '2009-04-24 16:06:37.000', '2008-11-12 12:11:14.000',
 '2008-09-19 14:55:28.000', '2008-10-29 16:16:40.000',
 '2008-10-21 08:04:34.000', '2008-09-25 12:01:51.000',
 ...
 '2024-04-11 10:55:03.000', '2024-04-04 10:33:49.000',
 '2024-05-09 10:04:25.000', '2024-04-02 11:50:48.000',
 '2024-05-27 11:22:30.000', '2024-04-01 14:02:54.000',
 '2024-03-04 09:53:08.000', '2024-05-02 16:49:10.000',
 '2024-03-04 16:02:39.000', '2024-04-10 12:51:57.000']
Length: 1109174, dtype: str
--------------------------------------------------------------------------------

dataabertura          | Nulos: 16
<StringArray>
['2005-07-06 08:32:23.000', '2006-01-17 12:10:53.000',
 '2005-07-06 11:28:47.000', '2006-01-18 15:35:29.000',
 '2005-07-06 15:36:03.000', '2006-01-23 12:58:47.000',
 '2005-03-28 10:20:39.000', '2005-03-31 09:59:40.000',
 '2005-07-08 15:19:39.000', '2005-07-08 15:46:05.000',
 ...
 '2024-03-04 08:09:59.000', '2024-02-29 08:12:41.000',
 '2024-03-26 16:40:32.000', '2024-02-20 11:39:28.000',
 '2024-03-21 10:18:22.000', '2024-01-24 09:49:10.000',
 '2024-01-29 13:30:56.000', '2024-02-02 08:41:32.000',
 '2024-01-26 09:41:28.000', '2024-02-06 12:10:56.000']
Length: 1434018, dtype: str
--------------------------------------------------------------------------------

codigoregiao          | Nulos: 0
<StringArray>
['5', '3', '1', '4', '2']
Length: 5, dtype: str
--------------------------------------------------------------------------------

regiao                | Nulos: 0
<StringArray>
['Centro-oeste', 'Sudeste', 'Norte', 'Sul', 'Nordeste']
Length: 5, dtype: str
--------------------------------------------------------------------------------

uf                    | Nulos: 0
<StringArray>
['GO', 'RJ', 'PA', 'AP', 'SC', 'MT', 'AM', 'PB', 'BA', 'ES', 'MS', 'PE', 'PI',
 'RN', 'CE', 'MG', 'AC', 'AL', 'SE', 'DF', 'MA', 'TO', 'RS', 'SP', 'PR', 'RO']
Length: 26, dtype: str
--------------------------------------------------------------------------------

strrazaosocial        | Nulos: 13
<StringArray>
[   'CBP SUL - COLCHÕES E ESPUMAS INDUSTRIAIS LTDA',
                                        'GRADIENTE',
                               'IGL INDÚSTRIA LTDA',
                   'UNILEVER BESTFOODS BRASIL LTDA',
       'EMPRESA BRASILEIRA DE TELECOMUNICAÇÕES S.A',
                 'LG ELECTRONICS DE SAO PAULO LTDA',
                          'MOTOROLA DO BRASIL LTDA',
                                  'TIM CELULAR S/A',
                          'PONTE IRMÃO & CIA LTDA.',
                                     'AMERICEL S/A',
 ...
                 'ERIKE DE OLIVEIRA SA 22942544813',
                              'MERCALF DIESEL LTDA',
   'RALIC CONSULTORIA E CORRETAGEM DE SEGUROS LTDA',
       'OWEM PAY INTERMEDIADORA DE PAGAMENTOS LTDA',
              'N26 SOCIEDADE DE CREDITO DIRETO S.A',
 'CENTRO DE FORMACAO DE C. FORTAL AUTO ESCOLA LTDA',
              'CERT CAR COMERCIO DE VEICULOS LTDA.',
                          'AGIL SECURITIZADORA S A',
     'CRYSTAL ESQUADRIAS DE ALUMINIO E VIDROS LTDA',
                            'R R DE SOUSA MENDONCA']
Length: 179075, dtype: str
--------------------------------------------------------------------------------

strnomefantasia       | Nulos: 295952
<StringArray>
[                               'LIMANSKY',
                                       nan,
             'ELIDA PONDS INDUSTRIAL LTDA',
                                'UNILEVER',
                        'EMBRATEL - LIVRE',
                                      'LG',
                 'MOTOROLA DO BRASIL LTDA',
                                     'TIM',
                         'LOJAS ESPLANADA',
                             'TIM CELULAR',
 ...
                                  'VOOFIT',
                         'PREMIUM TURISMO',
                             'ERIKE PECAS',
                          'MERCALF DIESEL',
                                'OWEM PAY',
     'N26 SOCIEDADE DE CREDITO DIRETO S.A',
                          'CERT CAR STORE',
 'CRYSTAL ESQUADRIAS DE ALUMINIO E VIDROS',
                'HUGO BOSS DO BRASIL LTDA',
                       'VERTICAL VEICULOS']
Length: 124804, dtype: str
--------------------------------------------------------------------------------

tipo                  | Nulos: 0
<StringArray>
['1', '0']
Length: 2, dtype: str
--------------------------------------------------------------------------------

numerocnpj            | Nulos: 76693
<StringArray>
['01350934000116', '43185362001936', '03085759000102', '01615814002066',
 '33530486000129', '01166372000155', '62288584000108', '04206050002809',
 '04228987008212', '04206050005220',
 ...
 '28091373000134',  '4807924000740', '10198495000169', '37839059000188',
 '40867163000190', '31801065000160', '35078477000174', '49000822000161',
 '57621054001910', '36556368000188']
Length: 133214, dtype: str
--------------------------------------------------------------------------------

radicalcnpj           | Nulos: 78750
<StringArray>
['01350934', '43185362', '03085759', '01615814', '33530486', '01166372',
 '62288584', '04206050', '04228987', '01685903',
 ...
 '10198495', '37839059', '40867163',  '2038584',  '1338617', '31801065',
 '35078477', '49000822',  '4620772', '36556368']
Length: 103925, dtype: str
--------------------------------------------------------------------------------

razaosocialrfb        | Nulos: 120534
<StringArray>
[      'CBP SUL - COLCHOES E ESPUMAS INDUSTRIAIS LTDA',
                                  'IGB ELETRONICA S.A',
      'UNILEVER BRASIL HIGIENE PESSOAL E LIMPEZA LTDA',
                     'UNILEVER BRASIL INDUSTRIAL LTDA',
 'EMPRESA BRASILEIRA DE TELECOMUNICACOES S A EMBRATEL',
                       'LG ELECTRONICS DO BRASIL LTDA',
                             'MOTOROLA DO BRASIL LTDA',
                                    'TIM CELULAR S.A.',
                              'PONTE IRMAO E CIA LTDA',
                                        'AMERICEL S/A',
 ...
                   'INSTITUTO ALCIDES D' ANDRADE LIMA',
              'ITAREMA AUTO PECAS SOROCABA LTDA  - ME',
                  'RAIMUNDO FERREIRA DIAS 00189110309',
                         'GODOY MOTO RACING LTDA - ME',
                   'METALOSA INDUSTRIA METALURGICA SA',
                          'NOVA GESTAO HOTELARIA LTDA',
                 'M. P. INSTITUTO LINGUISTICO LTDA ME',
                           'CENTRO DOS OCULOS LTDA ME',
             'PREMIUM TL TURISMO E NEGOCIOS LTDA - ME',
      'RALIC CONSULTORIA E CORRETAGEM DE SEGUROS LTDA']
Length: 91540, dtype: str
--------------------------------------------------------------------------------

nomefantasiarfb       | Nulos: 990934
<StringArray>
[                            nan,  'ELIDA PONDS INDUSTRIAL LTDA.',
                           'TIM',                     'ESPLANADA',
              'TIM CELULAR S.A.',                         'CLARO',
                'RICARDO ELETRO',            'LIDER REFRIGERACAO',
                          'VIVO',                 'DIRECAO GERAL',
 ...
                  'BRUMA TELHAS',                       'VALANNA',
               'MERCADINHO REAL',  'HOSPITAL MEMORIAL GUARARAPES',
            'ITAVEMA AUTO PECAS',       'CN SEGURANCA ELETRONICA',
             'GODOY MOTO RACING',                      'METALOSA',
                       'LEXICAL', 'PAULO TIBERIO PESSOA NOGUEIRA']
Length: 57350, dtype: str
--------------------------------------------------------------------------------

cnaeprincipal         | Nulos: 124596
<StringArray>
['3104700', '2640000', '2063100', '1031700', '6110899', '2622100', '4752100',
 '6120501', '4755502', '9521500',
 ...
 '4622200', '4681802', '3240002', '0111399', '4637104',  '220902',  '311604',
  '151201',  '810099', '1111902']
Length: 1029, dtype: str
--------------------------------------------------------------------------------

desccnaeprincipal     | Nulos: 142916
<StringArray>
[                                                                                                       'FABRICAÇÃO
DE COLCHÕES',
                                     'FABRICAÇÃO DE APARELHOS DE RECEPÇÃO, REPRODUÇÃO, GRAVAÇÃO E AMPLIFICAÇÃO DE
ÁUDIO E VÍDEO',
                                                         'FABRICAÇÃO DE COSMÉTICOS, PRODUTOS DE PERFUMARIA E DE
HIGIENE PESSOAL',
                                                                                             'FABRICAÇÃO DE
CONSERVAS DE FRUTAS',
                                                          'SERVIÇOS DE TELECOMUNICAÇÕES POR FIO NÃO ESPECIFICADOS
ANTERIORMENTE',
                                                                    'FABRICAÇÃO DE PERIFÉRICOS PARA EQUIPAMENTOS DE
INFORMÁTICA',
                                                   'COMÉRCIO VAREJISTA ESPECIALIZADO DE EQUIPAMENTOS DE TELEFONIA E
COMUNICAÇÃO',
                                                                                                       'TELEFONIA
MÓVEL CELULAR',
                                                                                    'COMERCIO VAREJISTA DE ARTIGOS
DE ARMARINHO',
                                           'REPARAÇÃO E MANUTENÇÃO DE EQUIPAMENTOS ELETROELETRÔNICOS DE USO PESSOAL
E DOMÉSTICO',
 ...
 'FABRICAÇÃO DE APARELHOS E UTENSÍLIOS PARA CORREÇÃO DE DEFEITOS FÍSICOS E APARELHOS ORTOPÉDICOS EM GERAL, EXCETO
SOB ENCOMENDA',
                                                                         'FABRICAÇÃO DE OUTRAS AGUARDENTES E
BEBIDAS DESTILADAS',
                                              'AGENCIAMENTO DE PROFISSIONAIS PARA ATIVIDADES ESPORTIVAS, CULTURAIS
E ARTÍSTICAS',
                                                  'FABRICAÇÃO DE GERADORES DE CORRENTE CONTÍNUA E ALTERNADA, PEÇAS
E ACESSÓRIOS',
          'SERVIÇOS DE OPERAÇÃO E FORNECIMENTO DE EQUIPAMENTOS PARA TRANSPORTE E ELEVAÇÃO DE CARGAS E PESSOAS PARA
USO EM OBRAS',
                                                                                          'COMÉRCIO ATACADISTA DE
LUBRIFICANTES',
                                                                                             'FABRICAÇÃO DE MASSAS
ALIMENTÍCIAS',
                                                              'FABRICAÇÃO DE SUCOS CONCENTRADOS DE FRUTAS,
HORTALIÇAS E LEGUMES',
                                                               'FABRICAÇÃO DE MOTORES PARA AUTOMÓVEIS, CAMIONETAS E
UTILITÁRIOS',
                                                                       'COMÉRCIO ATACADISTA DE CIGARROS,
CIGARRILHAS E CHARUTOS']
Length: 1715, dtype: str
--------------------------------------------------------------------------------

atendida              | Nulos: 0
<StringArray>
['S', 'N']
Length: 2, dtype: str
--------------------------------------------------------------------------------

codigoassunto         | Nulos: 14
<StringArray>
['100', '146', '224', '186', '101', '187',  '92',  '95',  '54', '103',
 ...
  '46', '209',  '40',  '32',  '41',  '52',  '47',   nan,  '43',  '44']
Length: 245, dtype: str
--------------------------------------------------------------------------------

descricaoassunto      | Nulos: 14
<StringArray>
[
'Colchão',

                     'Aparelho DVD',
                                                                                   'Produto Para Uso Veterinário (
Medicamento / Sabonete / Shampoo )',
                                                                                     'Telefonia Fixa ( Plano de
Expansão / Compra e Venda / Locação )',
                                                                                                 'Telefone (
Convencional, Celular, Interfone, Etc. )',

                'Telefonia Celular',
                                                                                                           'Máquina
de Lavar Roupa / Louça e Secadora',
                                                                                                               'Apa
relho de Som ( Gravador, 3x1, CD )',

                'Cartão de Crédito',
                                                   'Artigo de Cozinha ( Coifa, Exaustor, Panela, Talher, Filtro de
Café, Porta-Filtro, Louças, Etc. )',
 ...
                                    'Especiarias e Condimentos (orÃ©gano, pimenta, cravo, canela, pÃ¡prica, noz
moscada, alho e cebola desidratados).',
                                                                                               'Sopas
(desidratadas, liofilizadas, latas e embaladas)',

            'CartÃµes de Descontos',
                                                                                                    'Temperos
prontos (ajinomoto, sal com alho, etc.)',
                                                                                                      'Venda
atravÃ©s de reembolso postal a domicilio',

                                nan,

                              'Sal',

                          'Vinagre',

             'Cartões de Descontos',
 'Domissanitário / Saneante ( Desinfetante / Detergente / Cera / Creolina / Sabão / Água Sanitária ) Desinfetante (
Inseticida / Raticida Doméstico )']
Length: 375, dtype: str
--------------------------------------------------------------------------------

codigoproblema        | Nulos: 65505
<StringArray>
[ '105',  '107',  '177',  '143',  '102',  '123',  '134',  '113',   '28',
  '194',
 ...
 '6920',  '729',  '276', '5553', '6660', '3699', '4778', '4286', '2250',
 '1463']
Length: 3782, dtype: str
--------------------------------------------------------------------------------

descricaoproblema     | Nulos: 65505
<StringArray>
[                                                                          'Produto entregue com danos/defeitos',
                                                                      'Não entrega/demora na entrega do produto',
                                                                        'Presença de sujidades/corpos estranhos',
                                                                      'Contrato - Rescisão/alteração unilateral',
                                                                       'Garantia (Abrangência, cobertura, etc.)',
                                                     'Vicio de qualidade (mal executado, inadequado, impróprio)',
                                                                                     'Cobrança indevida/abusiva',
                                                                                    'Falta de peca de reposição',
                                                                                            'Cobrança indevida.',
                                'Documentos: não fornecimento (escolares, recibo, nota, fiscal, vaucher , etc.)',
 ...
                                               'Qualidade da construção (vícios, vazamentos, impermeabilização)',
                                     'Acidente de Consumo (produto/serviço causou danos pessoais ao consumidor)',
                                      'Tarifa de Cartão de Crédito – Cobrança Indevida (anuidade, 2ª via, etc.)',
                                                                  'Tarifas Bancárias – Cobrança não autorizada.',
                'Tarifas Bancárias – Divulgação inadequada / não divulgação na agência ou no sítio da Internet.',
                                         'CET – Divulgação inadequada / não divulgação nas peças publicitárias.',
 'SAC – Acesso ao serviço (onerosidade, problemas no menu, indisponibilidade, inacessibilidade aos deficientes)',
                                    'SAC – Cancelamento de serviço (retenção, demora, não envio do comprovante)',
                                            'CET – Não fornecimento de planilha de cálculo / Recusa de cálculo.',
      'SAC – Resolução de demandas (ausência de resposta, excesso de prazo, não suspensão imediata da cobrança)']
Length: 374, dtype: str
--------------------------------------------------------------------------------

sexoconsumidor        | Nulos: 0
<StringArray>
['M', 'F', 'OUTROS']
Length: 3, dtype: str
--------------------------------------------------------------------------------

faixaetariaconsumidor | Nulos: 0
<StringArray>
['entre 61 a 70 anos', 'entre 51 a 60 anos', 'entre 21 a 30 anos',
 'entre 41 a 50 anos', 'entre 31 a 40 anos',    'mais de 70 anos',
      'Nao Informada',        'até 20 anos',      'Nao se aplica',
       'atÃ© 20 anos']
Length: 10, dtype: str
--------------------------------------------------------------------------------

cepconsumidor         | Nulos: 132876
<StringArray>
['74680330', '23510240', '74775010', '20710270', '74000000', '26480440',
 '66030130',        nan, '75200000', '74230110',
 ...
 '75513466', '60830080', '60714690', '60530080', '60020260', '60525004',
 '60834560', '60740545', '60360575', '60440544']
Length: 305552, dtype: str
--------------------------------------------------------------------------------

--- Contagem de Valores Únicos por Coluna ---

dataarquivamento         1109174
dataabertura             1434018
codigoregiao                   5
regiao                         5
uf                            26
strrazaosocial            179075
strnomefantasia           124804
tipo                           2
numerocnpj                133214
radicalcnpj               103925
razaosocialrfb             91540
nomefantasiarfb            57350
cnaeprincipal               1029
desccnaeprincipal           1715
atendida                       2
codigoassunto                245
descricaoassunto             375
codigoproblema              3782
descricaoproblema            374
sexoconsumidor                 3
faixaetariaconsumidor         10
cepconsumidor             305552
ano_origem                    16
dtype: int64

#

### 3.1. Padronização Categórica: `faixaetariaconsumidor`
A inspeção da coluna de faixa etária revelou ruídos de codificação de caracteres (ex: `atÃ© 20 anos`) e falta de padronização nas nomenclaturas textuais. 

A estratégia aplicada utiliza um dicionário de mapeamento (`.replace()`) para agrupar as faixas em strings curtas e limpas (ex: `21 a 30`), eliminando redundâncias verbais como "entre" e "anos". Entradas não aplicáveis ou não informadas foram unificadas sob a flag `NAO INFORMADA`.

In [10]:
### Função para checarmos se a limpeza funcionou
def print_tabela_quantidade_registros(nome_coluna_dataframe : str, titulo_tabela_print : str, coluna_print : str):
    distribuicao = df_final[nome_coluna_dataframe].value_counts()

    console = Console()
    tabela = Table(title=titulo_tabela_print, show_header=True, header_style="bold magenta")
    tabela.add_column(coluna_print, style="cyan", justify="left")
    tabela.add_column("Quantidade de Registros", style="green", justify="right")

    for valor, quantidade in distribuicao.items():
        tabela.add_row(valor, f"{quantidade:,}".replace(",", ".")) # Formata número com pontos ao invés de vírgulas

    console.print(tabela)
    print("-" * 60)


print_tabela_quantidade_registros('faixaetariaconsumidor', 'Auditoria: Distribuição de Faixa Etária Pré-Limpeza', 'Faixa Etária') # ANTES


### Padronização das faixas etárias
padrao_faixa_etaria = {
    'mais de 70 anos'    : '70+',
    'entre 61 a 70 anos' : '61 a 70',
    'entre 51 a 60 anos' : '51 a 60',
    'entre 41 a 50 anos' : '41 a 50',
    'entre 31 a 40 anos' : '31 a 40',
    'entre 21 a 30 anos' : '21 a 30',
    'atÃ© 20 anos'       : '0 a 20',            # Erro de encoding afetando 27458 linhas
    'até 20 anos'        : '0 a 20', 
    'Nao Informada'      : 'NAO INFORMADA',
    'Nao se aplica'      : 'NAO INFORMADA'
}
df_final['faixaetariaconsumidor'] = df_final['faixaetariaconsumidor'].replace(padrao_faixa_etaria)


### PRINT DOS RESULTADOS DA AUDITORIA
print_tabela_quantidade_registros('faixaetariaconsumidor', 'Auditoria: Distribuição de Faixa Etária Pós-Limpeza', 'Faixa Etária') # DEPOIS
print_diagnostico('faixaetariaconsumidor')

    Auditoria: Distribuição de Faixa Etária
                  Pré-Limpeza
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Faixa Etária       ┃ Quantidade de Registros ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ entre 31 a 40 anos │                 409.562 │
│ entre 41 a 50 anos │                 351.153 │
│ entre 21 a 30 anos │                 292.079 │
│ entre 51 a 60 anos │                 279.763 │
│ entre 61 a 70 anos │                 186.702 │
│ Nao Informada      │                 160.488 │
│ mais de 70 anos    │                  92.540 │
│ atÃ© 20 anos       │                  27.458 │
│ até 20 anos        │                   1.489 │
│ Nao se aplica      │                     740 │
└────────────────────┴─────────────────────────┘

------------------------------------------------------------

  Auditoria: Distribuição de Faixa Etária
                Pós-Limpeza
┏━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Faixa Etária  ┃ Quantidade de Registros ┃
┡━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 31 a 40       │                 409.562 │
│ 41 a 50       │                 351.153 │
│ 21 a 30       │                 292.079 │
│ 51 a 60       │                 279.763 │
│ 61 a 70       │                 186.702 │
│ NAO INFORMADA │                 161.228 │
│ 70+           │                  92.540 │
│ 0 a 20        │                  28.947 │
└───────────────┴─────────────────────────┘

------------------------------------------------------------

faixaetariaconsumidor | Nulos: 0
<StringArray>
[      '61 a 70',       '51 a 60',       '21 a 30',       '41 a 50',
       '31 a 40',           '70+', 'NAO INFORMADA',        '0 a 20']
Length: 8, dtype: str
--------------------------------------------------------------------------------

### 3.2. Padronização das demais colunas

In [11]:
print(Panel("[bold bright_magenta]Iniciando Tratamentos Finais e Padronização...[/]", expand=False))

# Tamanho original para calcularmos as métricas de perda
quantidade_linhas_antes = len(df_final) 

# Descarte Final de Nulos Estruturais, são poquíssimas linhas perdidas, mas que contribuiram para a modelagem do data warehouse
df_final = df_final.dropna(subset=[
    'dataabertura', 'dataarquivamento', 
    'codigoassunto', 'descricaoassunto'
])



### PRINT DOS RESULTADOS DA AUDITORIA
linhas_descartadas = quantidade_linhas_antes - len(df_final)
porcentagem_perda = (linhas_descartadas / quantidade_linhas_antes) * 100 if quantidade_linhas_antes > 0 else 0

print(f"[bold green]Limpeza concluída com sucesso![/]")
print(f"Total de linhas antes:  [cyan]{quantidade_linhas_antes}[/]")
print(f"Total de linhas válidas:[bold cyan] {len(df_final)}[/]")
print(f"Linhas descartadas:     [red]{linhas_descartadas}[/] ({porcentagem_perda:.4f}%)")
print("-" * 60)

print_diagnostico('dataabertura')
print_diagnostico('dataarquivamento')
print_diagnostico('codigoassunto')
print_diagnostico('descricaoassunto')

# Verificação final de nulidade global 
total_nulos_restantes = df_final.isnull().sum().sum()

print(f"[bold bright_green]STATUS: Base Pronta para Modelagem![/]")
print(f"Total de Linhas Consolidadas: [bold cyan]{len(df_final):,}[/]".replace(",", "."))
print(f"Nulos Residuais na Base: [bold {'red' if total_nulos_restantes > 0 else 'green'}]{total_nulos_restantes}[/]")


### NOTA: note que os nulos restantes estão distribuídos em locais onde realmente esperamos a existência de nulos.
# nomefantasiarfb: ~990 mil nulos
# strnomefantasia: ~295 mil nulos
# desccnaeprincipal: ~142 mil nulos
# cepconsumidor: ~132 mil nulos

╭────────────────────────────────────────────────╮
│ Iniciando Tratamentos Finais e Padronização... │
╰────────────────────────────────────────────────╯

Limpeza concluída com sucesso!

Total de linhas antes:  1801974

Total de linhas válidas: 1801931

Linhas descartadas:     43 (0.0024%)

------------------------------------------------------------

dataabertura          | Nulos: 0
<StringArray>
['2005-07-06 08:32:23.000', '2006-01-17 12:10:53.000',
 '2005-07-06 11:28:47.000', '2006-01-18 15:35:29.000',
 '2005-07-06 15:36:03.000', '2006-01-23 12:58:47.000',
 '2005-03-28 10:20:39.000', '2005-03-31 09:59:40.000',
 '2005-07-08 15:19:39.000', '2005-07-08 15:46:05.000',
 ...
 '2024-03-04 08:09:59.000', '2024-02-29 08:12:41.000',
 '2024-03-26 16:40:32.000', '2024-02-20 11:39:28.000',
 '2024-03-21 10:18:22.000', '2024-01-24 09:49:10.000',
 '2024-01-29 13:30:56.000', '2024-02-02 08:41:32.000',
 '2024-01-26 09:41:28.000', '2024-02-06 12:10:56.000']
Length: 1434009, dtype: str
--------------------------------------------------------------------------------

dataarquivamento      | Nulos: 0
<StringArray>
['2009-01-21 15:29:29.000', '2009-05-12 12:05:08.000',
 '2009-04-23 08:52:31.000', '2009-07-23 11:57:40.000',
 '2009-04-24 16:06:37.000', '2008-11-12 12:11:14.000',
 '2008-09-19 14:55:28.000', '2008-10-29 16:16:40.000',
 '2008-10-21 08:04:34.000', '2008-09-25 12:01:51.000',
 ...
 '2024-04-11 10:55:03.000', '2024-04-04 10:33:49.000',
 '2024-05-09 10:04:25.000', '2024-04-02 11:50:48.000',
 '2024-05-27 11:22:30.000', '2024-04-01 14:02:54.000',
 '2024-03-04 09:53:08.000', '2024-05-02 16:49:10.000',
 '2024-03-04 16:02:39.000', '2024-04-10 12:51:57.000']
Length: 1109173, dtype: str
--------------------------------------------------------------------------------

codigoassunto         | Nulos: 0
<StringArray>
['100', '146', '224', '186', '101', '187',  '92',  '95',  '54', '103',
 ...
  '11',  '46', '209',  '40',  '32',  '41',  '52',  '47',  '43',  '44']
Length: 244, dtype: str
--------------------------------------------------------------------------------

descricaoassunto      | Nulos: 0
<StringArray>
[
'Colchão',

                     'Aparelho DVD',
                                                                                   'Produto Para Uso Veterinário (
Medicamento / Sabonete / Shampoo )',
                                                                                     'Telefonia Fixa ( Plano de
Expansão / Compra e Venda / Locação )',
                                                                                                 'Telefone (
Convencional, Celular, Interfone, Etc. )',

                'Telefonia Celular',
                                                                                                           'Máquina
de Lavar Roupa / Louça e Secadora',
                                                                                                               'Apa
relho de Som ( Gravador, 3x1, CD )',

                'Cartão de Crédito',
                                                   'Artigo de Cozinha ( Coifa, Exaustor, Panela, Talher, Filtro de
Café, Porta-Filtro, Louças, Etc. )',
 ...
                                                                                             'Tomate e derivados
(in natura, extratos, molhos, polpa)',
                                    'Especiarias e Condimentos (orÃ©gano, pimenta, cravo, canela, pÃ¡prica, noz
moscada, alho e cebola desidratados).',
                                                                                               'Sopas
(desidratadas, liofilizadas, latas e embaladas)',

            'CartÃµes de Descontos',
                                                                                                    'Temperos
prontos (ajinomoto, sal com alho, etc.)',
                                                                                                      'Venda
atravÃ©s de reembolso postal a domicilio',

                              'Sal',

                          'Vinagre',

             'Cartões de Descontos',
 'Domissanitário / Saneante ( Desinfetante / Detergente / Cera / Creolina / Sabão / Água Sanitária ) Desinfetante (
Inseticida / Raticida Doméstico )']
Length: 374, dtype: str
--------------------------------------------------------------------------------

STATUS: Base Pronta para Modelagem!

Total de Linhas Consolidadas: 1.801.931

Nulos Residuais na Base: 2094138

# Missão 1
Agora, converte-se alguns dos tipos do dataframe para coerência com o contexto e usabilidade de análise

## Conversão de datas

Converter dataarquivamento e dataabertura para tipos de data (timestamp)

In [12]:
#já aviso que isso demora para caramba, mas padroniza tudo num modelo só
df_final['dataarquivamento'] = pd.to_datetime(
    df_final['dataarquivamento'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [13]:
df_final['dataabertura'] = pd.to_datetime(
    df_final['dataabertura'],
    format='mixed',
    dayfirst=True,
    errors='coerce'
)

In [14]:
pd.set_option('display.max_columns', None)

pd.set_option('display.max_rows', None)

df_final.head(5)

,dataarquivamento,dataabertura,codigoregiao,regiao,uf,strrazaosocial,strnomefantasia,tipo,numerocnpj,radicalcnpj,razaosocialrfb,nomefantasiarfb,cnaeprincipal,desccnaeprincipal,atendida,codigoassunto,descricaoassunto,codigoproblema,descricaoproblema,sexoconsumidor,faixaetariaconsumidor,cepconsumidor,ano_origem
0,2009-01-21 15:29:29,2005-06-07 08:32:23,5,Centro-oeste,GO,CBP SUL - COLCHÕES E ESPUMAS INDUSTRIAIS LTDA,LIMANSKY,1,01350934000116,01350934,CBP SUL - COLCHOES E ESPUMAS INDUSTRIAIS LTDA,NaN,3104700,FABRICAÇÃO DE COLCHÕES,S,100,Colchão,105,Produto entregue com danos/defeitos,M,61 a 70,74680330,2009
1,2009-12-05 12:05:08,2006-01-17 12:10:53,3,Sudeste,RJ,GRADIENTE,NaN,1,43185362001936,43185362,IGB ELETRONICA S.A,NaN,2640000,"FABRICAÇÃO DE APARELHOS DE RECEPÇÃO, REPRODUÇÃ...",N,146,Aparelho DVD,107,Não entrega/demora na entrega do produto,F,51 a 60,23510240,2009
2,2009-04-23 08:52:31,2005-06-07 11:28:47,5,Centro-oeste,GO,IGL INDÚSTRIA LTDA,ELIDA PONDS INDUSTRIAL LTDA,1,03085759000102,03085759,UNILEVER BRASIL HIGIENE PESSOAL E LIMPEZA LTDA,ELIDA PONDS INDUSTRIAL LTDA.,2063100,"FABRICAÇÃO DE COSMÉTICOS, PRODUTOS DE PERFUMAR...",N,224,Produto Para Uso Veterinário ( Medicamento / S...,177,Presença de sujidades/corpos estranhos,F,21 a 30,74775010,2009
3,2009-04-23 08:52:31,2005-06-07 11:28:47,5,Centro-oeste,GO,UNILEVER BESTFOODS BRASIL LTDA,UNILEVER,1,01615814002066,01615814,UNILEVER BRASIL INDUSTRIAL LTDA,NaN,1031700,FABRICAÇÃO DE CONSERVAS DE FRUTAS,N,224,Produto Para Uso Veterinário ( Medicamento / S...,177,Presença de sujidades/corpos estranhos,F,21 a 30,74775010,2009
4,2009-07-23 11:57:40,2006-01-18 15:35:29,3,Sudeste,RJ,EMPRESA BRASILEIRA DE TELECOMUNICAÇÕES S.A,EMBRATEL - LIVRE,1,33530486000129,33530486,EMPRESA BRASILEIRA DE TELECOMUNICACOES S A EMB...,NaN,6110899,SERVIÇOS DE TELECOMUNICAÇÕES POR FIO NÃO ESPEC...,S,186,Telefonia Fixa ( Plano de Expansão / Compra e ...,143,Contrato - Rescisão/alteração unilateral,F,41 a 50,20710270,2009

In [15]:
#exibição dos tipos
df_final.info()

<class 'pandas.DataFrame'>
Index: 1801931 entries, 0 to 1801979
Data columns (total 23 columns):
 #   Column                 Dtype
---  ------                 -----
 0   dataarquivamento       datetime64[us]
 1   dataabertura           datetime64[us]
 2   codigoregiao           str
 3   regiao                 str
 4   uf                     str
 5   strrazaosocial         str
 6   strnomefantasia        str
 7   tipo                   str
 8   numerocnpj             str
 9   radicalcnpj            str
 10  razaosocialrfb         str
 11  nomefantasiarfb        str
 12  cnaeprincipal          str
 13  desccnaeprincipal      str
 14  atendida               str
 15  codigoassunto          str
 16  descricaoassunto       str
 17  codigoproblema         str
 18  descricaoproblema      str
 19  sexoconsumidor         str
 20  faixaetariaconsumidor  str
 21  cepconsumidor          str
 22  ano_origem             str
dtypes: datetime64[us](2), str(21)
memory usage: 329.9 MB

## Conversão de códigos para int

Também é necessário converter alguns códigos numéricos para o tipo inteiro. 
são eles:
- codigoregiao
- codigoassunto
- codigoproblema
- tipo
- ano_origem

In [16]:
#convertendo todas ao mesmo tempo
colunas = [
    'codigoregiao',
    'codigoassunto',
    'codigoproblema',
    'tipo',
    'ano_origem'
]

for coluna in colunas:
    serie = pd.to_numeric(df_final[coluna], errors='coerce')

    # Mantém apenas valores inteiros
    serie = serie.where(serie.isna() | (serie % 1 == 0))

    df_final[coluna] = serie.astype('Int64')

In [17]:
pd.set_option('display.max_columns', None)

pd.set_option('display.max_rows', None)

df_final.head(5)

,dataarquivamento,dataabertura,codigoregiao,regiao,uf,strrazaosocial,strnomefantasia,tipo,numerocnpj,radicalcnpj,razaosocialrfb,nomefantasiarfb,cnaeprincipal,desccnaeprincipal,atendida,codigoassunto,descricaoassunto,codigoproblema,descricaoproblema,sexoconsumidor,faixaetariaconsumidor,cepconsumidor,ano_origem
0,2009-01-21 15:29:29,2005-06-07 08:32:23,5,Centro-oeste,GO,CBP SUL - COLCHÕES E ESPUMAS INDUSTRIAIS LTDA,LIMANSKY,1,01350934000116,01350934,CBP SUL - COLCHOES E ESPUMAS INDUSTRIAIS LTDA,NaN,3104700,FABRICAÇÃO DE COLCHÕES,S,100,Colchão,105,Produto entregue com danos/defeitos,M,61 a 70,74680330,2009
1,2009-12-05 12:05:08,2006-01-17 12:10:53,3,Sudeste,RJ,GRADIENTE,NaN,1,43185362001936,43185362,IGB ELETRONICA S.A,NaN,2640000,"FABRICAÇÃO DE APARELHOS DE RECEPÇÃO, REPRODUÇÃ...",N,146,Aparelho DVD,107,Não entrega/demora na entrega do produto,F,51 a 60,23510240,2009
2,2009-04-23 08:52:31,2005-06-07 11:28:47,5,Centro-oeste,GO,IGL INDÚSTRIA LTDA,ELIDA PONDS INDUSTRIAL LTDA,1,03085759000102,03085759,UNILEVER BRASIL HIGIENE PESSOAL E LIMPEZA LTDA,ELIDA PONDS INDUSTRIAL LTDA.,2063100,"FABRICAÇÃO DE COSMÉTICOS, PRODUTOS DE PERFUMAR...",N,224,Produto Para Uso Veterinário ( Medicamento / S...,177,Presença de sujidades/corpos estranhos,F,21 a 30,74775010,2009
3,2009-04-23 08:52:31,2005-06-07 11:28:47,5,Centro-oeste,GO,UNILEVER BESTFOODS BRASIL LTDA,UNILEVER,1,01615814002066,01615814,UNILEVER BRASIL INDUSTRIAL LTDA,NaN,1031700,FABRICAÇÃO DE CONSERVAS DE FRUTAS,N,224,Produto Para Uso Veterinário ( Medicamento / S...,177,Presença de sujidades/corpos estranhos,F,21 a 30,74775010,2009
4,2009-07-23 11:57:40,2006-01-18 15:35:29,3,Sudeste,RJ,EMPRESA BRASILEIRA DE TELECOMUNICAÇÕES S.A,EMBRATEL - LIVRE,1,33530486000129,33530486,EMPRESA BRASILEIRA DE TELECOMUNICACOES S A EMB...,NaN,6110899,SERVIÇOS DE TELECOMUNICAÇÕES POR FIO NÃO ESPEC...,S,186,Telefonia Fixa ( Plano de Expansão / Compra e ...,143,Contrato - Rescisão/alteração unilateral,F,41 a 50,20710270,2009

In [18]:
df_final.info()

<class 'pandas.DataFrame'>
Index: 1801931 entries, 0 to 1801979
Data columns (total 23 columns):
 #   Column                 Dtype
---  ------                 -----
 0   dataarquivamento       datetime64[us]
 1   dataabertura           datetime64[us]
 2   codigoregiao           Int64
 3   regiao                 str
 4   uf                     str
 5   strrazaosocial         str
 6   strnomefantasia        str
 7   tipo                   Int64
 8   numerocnpj             str
 9   radicalcnpj            str
 10  razaosocialrfb         str
 11  nomefantasiarfb        str
 12  cnaeprincipal          str
 13  desccnaeprincipal      str
 14  atendida               str
 15  codigoassunto          Int64
 16  descricaoassunto       str
 17  codigoproblema         Int64
 18  descricaoproblema      str
 19  sexoconsumidor         str
 20  faixaetariaconsumidor  str
 21  cepconsumidor          str
 22  ano_origem             Int64
dtypes: Int64(5), datetime64[us](2), str(16)
memory usage: 338.5 MB

## Conclusão do Casting

O único problema encontrado foi um valor anômalo em `cepconsumidor` (verificação em série das colunas esperadas) que foi resolvido aplicando o casting Int64 com NaN para exceções.

Além disso, o casting de str para datatime também ocorreu sem problemas, colocando ocasionalemnte NaN em valores não esperados (os quais não foram achados no diagnóstico)

## Missão 2
Setup do Postgres:

In [19]:
from sqlalchemy import create_engine, text

engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/procons_sindec"
)

with engine.connect() as conn:
    result = conn.execute(text("SELECT 1"))
    print("Conexão OK!", result.fetchone())

Conexão OK! (1,)

## Missão 3

Agora começamos a fase da divisão do df_final em tabelas de fato e de dimensão, pra melhorar o desempenho e organização dos dados.

### Criação das tabelas dimensão

In [20]:
# essa sequencia de código cria os tipos da tabela dimensão 
# já fazendo a ação de remover as duplicatas e criando o indice sequencial

# Dimensão consumidor 
dim_consumidor = (
    df_final[['sexoconsumidor', 'faixaetariaconsumidor']]
    .drop_duplicates()
    .reset_index(drop=True)
    .reset_index()
    .rename(columns={'index': 'id_consumidor_sk'})
)

# Dimensão fornecedor (usar campos com sufixo rfb + radicalcnpj)
dim_fornecedor = (
    df_final[['numerocnpj', 'radicalcnpj', 'razaosocialrfb', 'nomefantasiarfb', 'cnaeprincipal', 'desccnaeprincipal']]
    .drop_duplicates()
    .reset_index(drop=True)
    .reset_index()
    .rename(columns={'index': 'id_fornecedor_sk'})
)

# Dimensão assunto 
dim_assunto = (
    df_final[['codigoassunto', 'descricaoassunto']]
    .drop_duplicates()
    .reset_index(drop=True)
    .reset_index()
    .rename(columns={'index': 'id_assunto_sk'})
)

# Dimensão problema
dim_problema = (
    df_final[['codigoproblema', 'descricaoproblema']]
    .drop_duplicates()
    .reset_index(drop=True)
    .reset_index()
    .rename(columns={'index': 'id_problema_sk'})
)

# 4) Dimensão localidade
dim_localidade = (
    df_final[['codigoregiao', 'regiao', 'uf', 'cepconsumidor']]
    .drop_duplicates()
    .reset_index(drop=True)
    .reset_index()
    .rename(columns={'index': 'id_localidade_sk'})
)

# 5) Dimensão tempo
dim_tempo = (
    df_final[['dataabertura']]
    .drop_duplicates()
    .sort_values('dataabertura')
    .reset_index(drop=True)
)

# aqui ele tá criando novas colunas:
# dia, mes, ano, trimestre e dia_semana
# separando os dados da dataabertura
dim_tempo['dia'] = dim_tempo['dataabertura'].dt.day
dim_tempo['mes'] = dim_tempo['dataabertura'].dt.month
dim_tempo['ano'] = dim_tempo['dataabertura'].dt.year
dim_tempo['trimestre'] = dim_tempo['dataabertura'].dt.quarter
dim_tempo['dia_semana'] = dim_tempo['dataabertura'].dt.day_name(locale='pt_BR.utf8')
dim_tempo = dim_tempo.reset_index().rename(columns={'index': 'id_tempo_sk'})

### Criação da tabela fato principal

In [21]:
import gc

print("Iniciando a modelagem da Tabela Fato (Modo Estrito)...")

# 1. Filtramos apenas o necessário para a memória
colunas_base = [
    'sexoconsumidor', 'faixaetariaconsumidor', 
    'razaosocialrfb', 'nomefantasiarfb', 'radicalcnpj',
    'codigoassunto', 'descricaoassunto', 
    'codigoproblema', 'descricaoproblema',
    'codigoregiao', 'regiao', 'uf', 'cepconsumidor', 
    'dataabertura', 'dataarquivamento', 
    'ano_origem', 'atendida'
]
fato = df_final[colunas_base].copy()
fato['dias_abertura_arquivamento'] = (fato['dataarquivamento'] - fato['dataabertura']).dt.days

# Guardamos o tamanho original para monitorização
tamanho_original = len(fato)
print(f"Tamanho inicial da Fato: {tamanho_original:,} linhas")

# --- FUNÇÃO DE MERGE SEGURO ---
def merge_seguro(df_fato, df_dimensao, chaves_join, colunas_retorno):
    """Garante que a dimensão é única antes de juntar, evitando Explosão Cartesiana."""
    
    # 1. Isola apenas as colunas que importam da dimensão
    dim_enxuta = df_dimensao[colunas_retorno].copy()
    
    # 2. A MÁGICA: Remove qualquer duplicata baseada nas chaves de junção
    dim_enxuta = dim_enxuta.drop_duplicates(subset=chaves_join)
    
    # 3. Faz o merge
    df_resultado = df_fato.merge(dim_enxuta, on=chaves_join, how='left')
    
    # 4. Apaga as colunas de texto da fato para liberar memória instantaneamente
    df_resultado.drop(columns=chaves_join, inplace=True)
    
    # 5. Auditoria de Explosão
    if len(df_resultado) > tamanho_original:
        print(f"[ALERTA] O merge com as chaves {chaves_join} causou explosão de {len(df_resultado) - tamanho_original} linhas!")
    
    return df_resultado

# --- APLICANDO OS MERGES ---

# Consumidor
fato = merge_seguro(fato, dim_consumidor, 
                    ['sexoconsumidor', 'faixaetariaconsumidor'], 
                    ['sexoconsumidor', 'faixaetariaconsumidor', 'id_consumidor_sk'])
print(f"Pós Consumidor: {len(fato):,} linhas")
gc.collect()

# Fornecedor
fato = merge_seguro(fato, dim_fornecedor, 
                    ['razaosocialrfb', 'nomefantasiarfb', 'radicalcnpj'], 
                    ['razaosocialrfb', 'nomefantasiarfb', 'radicalcnpj', 'id_fornecedor_sk'])
print(f"Pós Fornecedor: {len(fato):,} linhas")
gc.collect()

# Assunto
fato = merge_seguro(fato, dim_assunto, 
                    ['codigoassunto', 'descricaoassunto'], 
                    ['codigoassunto', 'descricaoassunto', 'id_assunto_sk'])
print(f"Pós Assunto: {len(fato):,} linhas")
gc.collect()

# Problema
fato = merge_seguro(fato, dim_problema, 
                    ['codigoproblema', 'descricaoproblema'], 
                    ['codigoproblema', 'descricaoproblema', 'id_problema_sk'])
print(f"Pós Problema: {len(fato):,} linhas")
gc.collect()

# Localidade
fato = merge_seguro(fato, dim_localidade, 
                    ['codigoregiao', 'regiao', 'uf', 'cepconsumidor'], 
                    ['codigoregiao', 'regiao', 'uf', 'cepconsumidor', 'id_localidade_sk'])
print(f"Pós Localidade: {len(fato):,} linhas")
gc.collect()

# Tempo (Cuidado extra com as datas)
fato = merge_seguro(fato, dim_tempo, 
                    ['dataabertura'], 
                    ['dataabertura', 'id_tempo_sk'])
# Removemos a data de arquivamento que sobrou
fato.drop(columns=['dataarquivamento'], inplace=True) 
print(f"Pós Tempo: {len(fato):,} linhas")
gc.collect()

# --- SELEÇÃO FINAL ---
fato_reclamacao = fato[
    [
        'id_consumidor_sk',
        'id_fornecedor_sk',
        'id_assunto_sk',
        'id_problema_sk',
        'id_localidade_sk',
        'id_tempo_sk',
        'ano_origem',
        'atendida',
        'dias_abertura_arquivamento'
    ]
].copy()

del fato
gc.collect()

print("\nCriação finalizada com sucesso! A RAM deve estar intacta agora.")

Iniciando a modelagem da Tabela Fato (Modo Estrito)...

Tamanho inicial da Fato: 1,801,931 linhas

Pós Consumidor: 1,801,931 linhas

Pós Fornecedor: 1,801,931 linhas

Pós Assunto: 1,801,931 linhas

Pós Problema: 1,801,931 linhas

Pós Localidade: 1,801,931 linhas

Pós Tempo: 1,801,931 linhas

Criação finalizada com sucesso! A RAM deve estar intacta agora.

* **Missão 4: Carga e Insights**
    * Tendo os *DataFrames* modelados corretamente e o ambiente no Postgre preparado, vamos carregá-los para o PostgreSQL via `.to_sql()`.
    * A ordem de inclusão das tabelas no ambiente PostgreSQL será: dim_consumidor, dim_fornecedor, dim_assunto, dim_problema, dim_localidade, dim_tempo e por último fato_reclamacao.

In [24]:
# carrega primeiro as tabelas de dimensao para o banco de dados do PostgreSQL usando o SQLAlchemy (a engine foi definida la em cima quando foi feito o teste de conexao com o servidor), se a tabela ja existir ele substitui (replace) e não inclui o index do dataframe
# a ordem de inclusao eh importante por causa das chaves estrangeiras inclusas na tabela fato, entao sempre as dimensoes sao incluidas primeiro e depois a fato
print(Panel("[bold bright_magenta]Iniciando Carga dos Dados Limpos (Pandas) no PostgreSQL...[/]", expand=False))


schema_alvo = "esquema_estrela_etl"

try:
    # primeira tabela a ser carregada: dim_consumidor
    dim_consumidor.to_sql('dim_consumidor', con=engine, schema=schema_alvo, if_exists='replace', index=False)
    # segunda tabela a ser carregada: dim_fornecedor
    dim_fornecedor.to_sql('dim_fornecedor', con=engine, schema=schema_alvo, if_exists='replace', index=False)
    # terceira tabela a ser carregada: dim_assunto
    dim_assunto.to_sql('dim_assunto', con=engine, schema=schema_alvo, if_exists='replace', index=False)
    # quarta tabela a ser carregada: dim_problema
    dim_problema.to_sql('dim_problema', con=engine, schema=schema_alvo, if_exists='replace', index=False)
    # quinta tabela a ser carregada: dim_localidade
    dim_localidade.to_sql('dim_localidade', con=engine, schema=schema_alvo, if_exists='replace', index=False)
    # sexta tabela a ser carregada: dim_tempo
    dim_tempo.to_sql('dim_tempo', con=engine, schema=schema_alvo, if_exists='replace', index=False)
    # setima e ultima tabela a ser carregada: fato_reclamacao
    fato_reclamacao.to_sql('fato_reclamacao', schema=schema_alvo, con=engine, if_exists='replace', index=False)

    print(f"[bold green]Sucesso![/] Tabelas salvas no schema '{schema_alvo}'.")


except Exception as e:
    print(f"[bold red]Erro crítico na carga:[/] {e}")

╭────────────────────────────────────────────────────────────╮
│ Iniciando Carga dos Dados Limpos (Pandas) no PostgreSQL... │
╰────────────────────────────────────────────────────────────╯

Sucesso! Tabelas salvas no schema 'esquema_estrela_etl'.

# Análises e Insights

Agora que todas as tabelas dimensão e fato foram devidamente carregadas no servidor do PostgreSQL, vamos criar 3 consultas de *Business Intelligence* (*BI*) para nos ajudar a gerar insights relevantes sobre os dados que estamos trabalhando. Essas consultas vão nos ajudar a responder algumas perguntas que queremos saber sobre o nosso banco de reclamações no PROCON.

In [39]:
# primeira pergunta: qual a média de dias entre a abertura e o arquivamento das reclamações?
query_media_dias = """
SELECT 
    AVG(dias_abertura_arquivamento) AS media_dias
FROM esquema_estrela_etl.fato_reclamacao
WHERE dias_abertura_arquivamento IS NOT NULL
"""

with engine.connect() as conn:
    resultado = conn.execute(text(query_media_dias))
    media_dias = resultado.fetchone()[0]
    print(f"Média de dias entre abertura e arquivamento: {media_dias:.2f} dias")

Média de dias entre abertura e arquivamento: 226.10 dias

In [40]:
# segunda pergunta: no ano de 2020, qual foi a região com maior número de reclamações?
query_regiao_2020 = """
SELECT 
    r.regiao, 
    COUNT(*) AS total_reclamacoes
FROM esquema_estrela_etl.fato_reclamacao f
JOIN esquema_estrela_etl.dim_localidade r ON f.id_localidade_sk = r.id_localidade_sk
WHERE f.ano_origem = 2020
GROUP BY r.regiao
ORDER BY total_reclamacoes DESC
LIMIT 1
"""

with engine.connect() as conn:
    resultado = conn.execute(text(query_regiao_2020))
    regiao_mais_reclamacoes = resultado.fetchone()
    print(f"Região com mais reclamações em 2020: {regiao_mais_reclamacoes[0]} com {regiao_mais_reclamacoes[1]:,} reclamações".replace(",", "."))

Região com mais reclamações em 2020: Sudeste com 3.901 reclamações

In [41]:
# terceira pergunta: qual é a distribuição de reclamações por faixa etária do consumidor para o ano de 2021?
query_faixa_etaria_2021 = """
SELECT 
    c.faixaetariaconsumidor, 
    COUNT(*) AS total_reclamacoes
FROM esquema_estrela_etl.fato_reclamacao f
JOIN esquema_estrela_etl.dim_consumidor c ON f.id_consumidor_sk = c.id_consumidor_sk
WHERE f.ano_origem = 2021
GROUP BY c.faixaetariaconsumidor
ORDER BY total_reclamacoes DESC
"""

with engine.connect() as conn:
    resultado = conn.execute(text(query_faixa_etaria_2021))
    print("Distribuição de reclamações por faixa etária em 2021:")
    for faixa, total in resultado:
        print(f"Faixa Etária: {faixa:<15} - Total de Reclamações: {total:,}".replace(",", "."))

Distribuição de reclamações por faixa etária em 2021:

Faixa Etária: 31 a 40         - Total de Reclamações: 1.615

Faixa Etária: 41 a 50         - Total de Reclamações: 1.509

Faixa Etária: 61 a 70         - Total de Reclamações: 1.500

Faixa Etária: 51 a 60         - Total de Reclamações: 1.373

Faixa Etária: NAO INFORMADA   - Total de Reclamações: 1.182

Faixa Etária: 21 a 30         - Total de Reclamações: 1.046

Faixa Etária: 70+             - Total de Reclamações: 642

Faixa Etária: 0 a 20          - Total de Reclamações: 138

In [ ]:
# Quarta pergunta: Estatísticas de distribuição do tempo de resolução
query_distribuicao_tempo = """
SELECT 
    MIN(dias_abertura_arquivamento) AS dias_minimo,
    MAX(dias_abertura_arquivamento) AS dias_maximo,
    AVG(dias_abertura_arquivamento) AS media_dias,
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY dias_abertura_arquivamento) AS mediana_dias,
    PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY dias_abertura_arquivamento) AS q1_dias,
    PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY dias_abertura_arquivamento) AS q3_dias
FROM fato_reclamacao
WHERE dias_abertura_arquivamento IS NOT NULL
"""

with engine.connect() as conn:
    resultado = conn.execute(text(query_distribuicao_tempo))
    stats = resultado.fetchone()
    print("📊 ESTATÍSTICAS DE TEMPO DE RESOLUÇÃO")
    print("=" * 70)
    print(f"Mínimo de dias:      {stats[0]}")
    print(f"Máximo de dias:      {stats[1]}")
    print(f"Média de dias:       {stats[2]:.2f}")
    print(f"Mediana de dias:     {stats[3]:.2f}")
    print(f"Q1 (25º percentil):  {stats[4]:.2f}")
    print(f"Q3 (75º percentil):  {stats[5]:.2f}")
    print(f"Amplitude:           {stats[1] - stats[0]} dias")

📊 ESTATÍSTICAS DE TEMPO DE RESOLUÇÃO

======================================================================

Mínimo de dias:      -335

Máximo de dias:      5795

Média de dias:       226.10

Mediana de dias:     116.00

Q1 (25º percentil):  32.00

Q3 (75º percentil):  282.00

Amplitude:           6130 dias

In [ ]:
# Quinta pergunta: Reclamações que levam mais de 90 dias (casos críticos)
query_casos_criticos = """
SELECT 
    COUNT(*) AS total_reclamacoes_90_plus,
    COUNT(*) * 100.0 / (SELECT COUNT(*) FROM fato_reclamacao WHERE dias_abertura_arquivamento IS NOT NULL) AS percentual,
    AVG(dias_abertura_arquivamento) AS media_dias_casos_criticos,
    MAX(dias_abertura_arquivamento) AS max_dias_casos_criticos
FROM fato_reclamacao
WHERE dias_abertura_arquivamento > 90 AND dias_abertura_arquivamento IS NOT NULL
"""

with engine.connect() as conn:
    resultado = conn.execute(text(query_casos_criticos))
    stats_criticos = resultado.fetchone()
    print("\n⚠️  ANÁLISE DE CASOS CRÍTICOS (>90 dias)")
    print("=" * 70)
    print(f"Total de reclamações com atraso:  {int(stats_criticos[0])}")
    print(f"Percentual do total:              {stats_criticos[1]:.2f}%")
    print(f"Média de dias (casos críticos):   {stats_criticos[2]:.2f}")
    print(f"Máximo de dias (caso extremo):    {int(stats_criticos[3])}")

⚠️  ANÁLISE DE CASOS CRÍTICOS (>90 dias)

======================================================================

Total de reclamações com atraso:  1015008

Percentual do total:              56.33%

Média de dias (casos críticos):   407.79

Máximo de dias (caso extremo):    5795

In [ ]:
# Sexta pergunta: Tipos de reclamação (assuntos) com resolução mais rápida
query_assuntos_rapidos = """
SELECT 
    a.descricaoassunto,
    COUNT(*) AS total_reclamacoes,
    AVG(f.dias_abertura_arquivamento) AS media_dias_resolucao,
    MIN(f.dias_abertura_arquivamento) AS min_dias,
    MAX(f.dias_abertura_arquivamento) AS max_dias
FROM fato_reclamacao f
JOIN dim_assunto a ON f.id_assunto_sk = a.id_assunto_sk
WHERE f.dias_abertura_arquivamento IS NOT NULL
GROUP BY a.descricaoassunto, a.id_assunto_sk
ORDER BY media_dias_resolucao ASC
LIMIT 10
"""

with engine.connect() as conn:
    resultado = conn.execute(text(query_assuntos_rapidos))
    print("\n⚡ TOP 10 ASSUNTOS COM RESOLUÇÃO MAIS RÁPIDA")
    print("=" * 100)
    print(f"{'Assunto':<50} {'Total':<10} {'Média (dias)':<15} {'Min':<10} {'Max':<10}")
    print("-" * 100)
    for row in resultado:
        print(f"{row[0]:<50} {int(row[1]):<10} {row[2]:<15.2f} {int(row[3]):<10} {int(row[4]):<10}")

⚡ TOP 10 ASSUNTOS COM RESOLUÇÃO MAIS RÁPIDA

====================================================================================================

Assunto                                            Total      Média (dias)    Min        Max

----------------------------------------------------------------------------------------------------

Diversão / Lazer / Cultura ( Teatro, Cinema, Casa Noturna, Videolocadora, Etc. ) 1          -271.00         -271
-271

CARTÕES DE DESCONTOS                               1          -58.00          -58        -58

Tomate e derivados (in natura, extratos, molhos, polpa) 5          -31.00          -196       124

Farináceos (fubá, polvilho, etc.)                  2          -23.00          -79        33

Cartões de Descontos                               1          -19.00          -19        -19

CartÃµes de Descontos                              5          12.80           -212       313

Venda por telemarketing                            37         38.59           -275       335

Açúcar / Mel                                       2          57.00           -29        143

Curso de Línguas                                   3          61.00           61         61

Sopas (desidratadas, liofilizadas, latas e embaladas) 3          63.67           26         139

In [ ]:
# Sétima pergunta: Tipos de reclamação (assuntos) com resolução mais lenta (gargalos)
query_assuntos_lentos = """
SELECT 
    a.descricaoassunto,
    COUNT(*) AS total_reclamacoes,
    AVG(f.dias_abertura_arquivamento) AS media_dias_resolucao,
    MIN(f.dias_abertura_arquivamento) AS min_dias,
    MAX(f.dias_abertura_arquivamento) AS max_dias
FROM fato_reclamacao f
JOIN dim_assunto a ON f.id_assunto_sk = a.id_assunto_sk
WHERE f.dias_abertura_arquivamento IS NOT NULL
GROUP BY a.descricaoassunto, a.id_assunto_sk
ORDER BY media_dias_resolucao DESC
LIMIT 10
"""

with engine.connect() as conn:
    resultado = conn.execute(text(query_assuntos_lentos))
    print("\n🐢 TOP 10 ASSUNTOS COM RESOLUÇÃO MAIS LENTA (GARGALOS)")
    print("=" * 100)
    print(f"{'Assunto':<50} {'Total':<10} {'Média (dias)':<15} {'Min':<10} {'Max':<10}")
    print("-" * 100)
    for row in resultado:
        print(f"{row[0]:<50} {int(row[1]):<10} {row[2]:<15.2f} {int(row[3]):<10} {int(row[4]):<10}")

🐢 TOP 10 ASSUNTOS COM RESOLUÇÃO MAIS LENTA (GARGALOS)

====================================================================================================

Assunto                                            Total      Média (dias)    Min        Max

----------------------------------------------------------------------------------------------------

Seguro                                             6          2666.67         365        3127

Vinagre                                            1          2652.00         2652       2652

Sal                                                1          2534.00         2534       2534

Conserva Animal (atum, sardinha, apresuntado, alite, feijoada, patÃª, etc.) 16         1361.06         28
3452

FarinÃ¡ceos (fubÃ¡, polvilho, etc.)                112        1356.47         -3         4319

Temperos prontos (ajinomoto, sal com alho, etc.)   12         1342.17         37         2386

Conserva Vegetal (azeitona, ervilha, milho, palmito, aspargo, cogumelo) em qualquer tipo de embalagem. 16
1106.38         -167       3875

BalanÃ§a (informaÃ§Ã£o nutricional, como valor calÃ³rico e relaÃ§Ã£o peso/altura) 17         1047.00         582
1229

PÃ³s para preparo (refresco, gelatina, pudim, bolos, pÃ£o de queijo, pizza e sorvete) 15         982.60
-112       2480

Especiarias e Condimentos (orÃ©gano, pimenta, cravo, canela, pÃ¡prica, noz moscada, alho e cebola desidratados). 15
956.67          -142       3406

In [ ]:
# Oitava pergunta: Taxa de atendimento vs tempo de resolução
query_atendimento_tempo = """
SELECT 
    atendida,
    COUNT(*) AS total_reclamacoes,
    AVG(dias_abertura_arquivamento) AS media_dias_resolucao,
    MIN(dias_abertura_arquivamento) AS min_dias,
    MAX(dias_abertura_arquivamento) AS max_dias,
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY dias_abertura_arquivamento) AS mediana_dias
FROM fato_reclamacao
WHERE dias_abertura_arquivamento IS NOT NULL
GROUP BY atendida
"""

with engine.connect() as conn:
    resultado = conn.execute(text(query_atendimento_tempo))
    print("\n✅ ANÁLISE: ATENDIMENTO vs TEMPO DE RESOLUÇÃO")
    print("=" * 100)
    print(f"{'Status':<15} {'Total':<15} {'Média (dias)':<15} {'Mediana':<15} {'Min':<10} {'Max':<10}")
    print("-" * 100)
    for row in resultado:
        status = "Atendida" if row[0] == "S" else "Não Atendida"
        print(f"{status:<15} {int(row[1]):<15} {row[2]:<15.2f} {row[5]:<15.2f} {int(row[3]):<10} {int(row[4]):<10}")

✅ ANÁLISE: ATENDIMENTO vs TEMPO DE RESOLUÇÃO

====================================================================================================

Status          Total           Média (dias)    Mediana         Min        Max

----------------------------------------------------------------------------------------------------

Não Atendida    686178          306.98          143.00          -335       5795

Atendida        1115753         176.36          100.00          -335       5608

In [ ]:
# Nona pergunta: Evolução temporal da eficiência (média de dias por ano)
query_eficiencia_anual = """
SELECT 
    f.ano_origem,
    COUNT(*) AS total_reclamacoes,
    AVG(f.dias_abertura_arquivamento) AS media_dias_resolucao,
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY f.dias_abertura_arquivamento) AS mediana_dias,
    COUNT(CASE WHEN f.dias_abertura_arquivamento > 90 THEN 1 END) AS casos_criticos_90_plus,
    COUNT(CASE WHEN f.dias_abertura_arquivamento > 90 THEN 1 END) * 100.0 / COUNT(*) AS percentual_criticos
FROM fato_reclamacao f
WHERE f.dias_abertura_arquivamento IS NOT NULL
GROUP BY f.ano_origem
ORDER BY f.ano_origem
"""

with engine.connect() as conn:
    resultado = conn.execute(text(query_eficiencia_anual))
    print("\n📈 EVOLUÇÃO TEMPORAL DA EFICIÊNCIA (MÉDIA DIAS POR ANO)")
    print("=" * 120)
    print(f"{'Ano':<6} {'Total':<12} {'Média (dias)':<15} {'Mediana':<15} {'Críticos (>90)':<18} {'% Críticos':<12}")
    print("-" * 120)
    for row in resultado:
        print(f"{int(row[0]):<6} {int(row[1]):<12} {row[2]:<15.2f} {row[3]:<15.2f} {int(row[4]):<18} {row[5]:<12.2f}%")

📈 EVOLUÇÃO TEMPORAL DA EFICIÊNCIA (MÉDIA DIAS POR ANO)

===================================================================================================================
=====

Ano    Total        Média (dias)    Mediana         Críticos (>90)     % Críticos

-------------------------------------------------------------------------------------------------------------------
-----

2009   104867       174.70          120.00          60669              57.85       %

2010   122662       192.91          129.00          72945              59.47       %

2011   153094       184.35          142.00          100080             65.37       %

2012   211076       239.28          139.00          131523             62.31       %

2013   268096       216.46          119.00          151681             56.58       %

2014   267764       184.50          104.00          144617             54.01       %

2015   255650       180.47          91.00           128183             50.14       %

2016   203485       233.91          99.00           107066             52.62       %

2017   42301        213.27          92.00           21549              50.94       %

2018   39033        154.41          87.00           18670              47.83       %

2019   17538        162.81          63.00           7825               44.62       %

2020   8006         279.03          202.00          5485               68.51       %

2021   9005         257.59          130.00          5304               58.90       %

2022   68286        797.29          203.00          44872              65.71       %

2023   17265        317.65          86.00           8298               48.06       %

2024   13803        228.49          71.00           6241               45.21       %

In [ ]:
# Décima pergunta: Fornecedores com maior tempo médio de resolução (problemas crônicos)
query_fornecedores_lentos = """
SELECT 
    SUBSTRING(f.razaosocialrfb, 1, 45) AS fornecedor,
    COUNT(*) AS total_reclamacoes,
    AVG(r.dias_abertura_arquivamento) AS media_dias_resolucao,
    COUNT(CASE WHEN r.dias_abertura_arquivamento > 90 THEN 1 END) AS casos_criticos
FROM fato_reclamacao r
JOIN dim_fornecedor f ON r.id_fornecedor_sk = f.id_fornecedor_sk
WHERE r.dias_abertura_arquivamento IS NOT NULL
GROUP BY f.razaosocialrfb, f.id_fornecedor_sk
HAVING COUNT(*) >= 50
ORDER BY media_dias_resolucao DESC
LIMIT 10
"""

with engine.connect() as conn:
    resultado = conn.execute(text(query_fornecedores_lentos))
    print("\n🏢 TOP 10 FORNECEDORES COM MAIOR ATRASO (MÍNIMO 50 RECLAMAÇÕES)")
    print("=" * 120)
    print(f"{'Fornecedor':<45} {'Total':<12} {'Média (dias)':<15} {'Críticos (>90)':<15}")
    print("-" * 120)
    for row in resultado:
        print(f"{row[0]:<45} {int(row[1]):<12} {row[2]:<15.2f} {int(row[3]):<15}")

🏢 TOP 10 FORNECEDORES COM MAIOR ATRASO (MÍNIMO 50 RECLAMAÇÕES)

===================================================================================================================
=====

Fornecedor                                    Total        Média (dias)    Críticos (>90)

-------------------------------------------------------------------------------------------------------------------
-----

CELLSHOP TELEFONES LTDA                       175          2019.47         175

SIEMENS ELETROELETRONICA LTDA                 157          1793.32         153

SS BENEFICIOS LTDA.                           59           1639.59         56

GUIMARAES E CAMPOS LTDA                       86           1495.01         86

SUPERMERCADO MODELO LTDA                      69           1465.23         66

DATA CENTER INFORMATICA LTDA                  64           1280.88         64

MARISA LOJAS S.A.                             111          1248.44         93

BANCO DO BRASIL SA                            51           1228.88         46

GLOBAL EXPRESS ASSISTENCIA TECNICA LTDA - EPP 88           1165.68         63

BANCO ABN AMRO REAL S.A.                      99           1155.80         88

In [ ]:
# Décima-primeira pergunta: Resumo executivo - Indicadores de qualidade consolidados
query_indicadores_qualidade = """
SELECT 
    COUNT(*) AS total_reclamacoes,
    COUNT(CASE WHEN atendida = 'S' THEN 1 END) AS atendidas,
    COUNT(CASE WHEN atendida = 'S' THEN 1 END) * 100.0 / COUNT(*) AS taxa_atendimento,
    COUNT(CASE WHEN dias_abertura_arquivamento IS NOT NULL AND dias_abertura_arquivamento > 90 THEN 1 END) AS atrasos_criticos,
    COUNT(CASE WHEN dias_abertura_arquivamento IS NOT NULL AND dias_abertura_arquivamento > 90 THEN 1 END) * 100.0 / COUNT(CASE WHEN dias_abertura_arquivamento IS NOT NULL THEN 1 END) AS taxa_atrasos_criticos,
    AVG(dias_abertura_arquivamento) AS media_geral_dias
FROM fato_reclamacao
"""

with engine.connect() as conn:
    resultado = conn.execute(text(query_indicadores_qualidade))
    kpis = resultado.fetchone()
    
    print("\n" + "=" * 100)
    print("📊 RESUMO EXECUTIVO - INDICADORES DE QUALIDADE E EFICIÊNCIA")
    print("=" * 100)
    print(f"✓ Total de Reclamações:           {int(kpis[0]):>20}")
    print(f"✓ Reclamações Atendidas:          {int(kpis[1]):>20}")
    print(f"✓ Taxa de Atendimento:            {kpis[2]:>19.2f}%")
    print(f"⚠️  Reclamações com Atraso (>90d):  {int(kpis[3]):>20}")
    print(f"⚠️  Taxa de Atrasos Críticos:       {kpis[4]:>19.2f}%")
    print(f"⏱️  Tempo Médio de Resolução:      {kpis[5]:>18.2f} dias")
    print("=" * 100)
    
    print("\n💡 RECOMENDAÇÕES:")
    print("-" * 100)
    
    if kpis[4] > 30:
        print(f"1. ⚠️  CRÍTICO: {kpis[4]:.1f}% das reclamações ultrapassam 90 dias.")
        print("   → Revisar processos de resolução e alocar mais recursos nos gargalos.")
    
    if kpis[2] < 70:
        print(f"2. ⚠️  ATENÇÃO: Taxa de atendimento de apenas {kpis[2]:.1f}%.")
        print("   → Investigar causas de não-atendimento e implementar ações corretivas.")
    
    if kpis[5] > 60:
        print(f"3. ⏱️  ALERTA: Tempo médio de resolução de {kpis[5]:.0f} dias é alto.")
        print("   → Otimizar fluxos de trabalho para reduzir tempo de resolução.")
    
    print("-" * 100)

====================================================================================================

📊 RESUMO EXECUTIVO - INDICADORES DE QUALIDADE E EFICIÊNCIA

====================================================================================================

✓ Total de Reclamações:                        1801931

✓ Reclamações Atendidas:                       1115753

✓ Taxa de Atendimento:                          61.92%

⚠️  Reclamações com Atraso (>90d):               1015008

⚠️  Taxa de Atrasos Críticos:                     56.33%

⏱️  Tempo Médio de Resolução:                  226.10 dias

====================================================================================================

💡 RECOMENDAÇÕES:

----------------------------------------------------------------------------------------------------

1. ⚠️  CRÍTICO: 56.3% das reclamações ultrapassam 90 dias.

   → Revisar processos de resolução e alocar mais recursos nos gargalos.

2. ⚠️  ATENÇÃO: Taxa de atendimento de apenas 61.9%.

   → Investigar causas de não-atendimento e implementar ações corretivas.

3. ⏱️  ALERTA: Tempo médio de resolução de 226 dias é alto.

   → Otimizar fluxos de trabalho para reduzir tempo de resolução.

----------------------------------------------------------------------------------------------------